# Generated by Django 5.0.12 on 2025-03-27 07:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import scaleos.shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0021_organizationstyling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to=scaleos.shared.models.CardModel.model_directory_path, verbose_name='card image')),
                ('card_description', models.TextField(blank=True, default='', verbose_name='card description')),
                ('public_key', models.UUIDField(editable=False, null=True, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True)),
                ('level', models.IntegerField(default=0, verbose_name='level')),
                ('square_metres', models.IntegerField(blank=True, null=True, verbose_name='square metres')),
                ('gps_surface', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='organizations.organization', verbose_name='organization')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'floor',
                'verbose_name_plural': 'floors',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('floor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.floor')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
            },
            bases=('buildings.floor',),
        ),
        migrations.CreateModel(
            name='Terrace',
            fields=[
                ('floor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.floor')),
            ],
            options={
                'verbose_name': 'terrace',
                'verbose_name_plural': 'terraces',
            },
            bases=('buildings.floor',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('floor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.floor')),
                ('in_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building', verbose_name='in building')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
            bases=('buildings.floor',),
        ),
    ]
