# Generated by Django 5.0.12 on 2025-06-03 08:40

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_rename_transition_durtion_floor_transition_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='buildings.floor', verbose_name='floor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
