# Generated by Django 5.0.12 on 2025-06-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_floorlayout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='in_building',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor_ptr',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
