# Generated by Django 5.0.12 on 2025-06-03 09:08

import autoslug.fields
import django.db.models.deletion
import scaleos.shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_remove_room_in_building_remove_room_floor_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('flip', 'Flip')], default='fade', max_length=50, verbose_name='every interval')),
                ('transition_interval', models.IntegerField(default=5000, help_text='in milliseconds', verbose_name='transition interval')),
                ('transition_duration', models.IntegerField(default=1500, help_text='in milliseconds', verbose_name='transition duration')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to=scaleos.shared.models.CardModel.model_directory_path, verbose_name='card image')),
                ('card_description', models.TextField(blank=True, default='', verbose_name='card description')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
                ('public_key', models.UUIDField(editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='card_description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='floor',
            name='card_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='floor',
            name='card_description_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='floor',
            name='card_description_nl',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='floor',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='floor',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='floor',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='floor',
            name='name_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('floor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.floor')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building', verbose_name='building')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
            bases=('buildings.floor',),
        ),
    ]
