# Generated by Django 5.0.12 on 2025-06-03 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_building_floor_card_description_de_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('hr', '0025_alter_person_birthday'),
        ('organizations', '0052_customer_b2bcustomer_b2ccustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='floor',
            name='organization',
        ),
        migrations.CreateModel(
            name='FloorTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='buildings.floor')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_floors', to='buildings.party')),
            ],
        ),
        migrations.CreateModel(
            name='FloorOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='buildings.floor')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning_floors', to='buildings.party')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='buildings.building')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_buildings', to='buildings.party')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='buildings.building')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning_buildings', to='buildings.party')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('party_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.party')),
                ('linked_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('buildings.party',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('party_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.party')),
                ('linked_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.person', verbose_name='person')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('buildings.party',),
        ),
    ]
