# Generated by Django 5.0.12 on 2025-06-03 13:33

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_party_remove_floor_organization_floortenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
    ]
