# Generated by Django 5.0.12 on 2025-06-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_floor_slug_alter_floor_name_alter_floor_name_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'bath room',
                'verbose_name_plural': 'bath rooms',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='BedRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'bedroom',
                'verbose_name_plural': 'bedrooms',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='FitnessRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'fitness room',
                'verbose_name_plural': 'fitness rooms',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'garage',
                'verbose_name_plural': 'garages',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'hotel room',
                'verbose_name_plural': 'hotel rooms',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'kitchen',
                'verbose_name_plural': 'kitchens',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='LaundryRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'laundry room',
                'verbose_name_plural': 'laundry rooms',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='LivingRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'living room',
                'verbose_name_plural': 'living rooms',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'meeting room',
                'verbose_name_plural': 'meeting rooms',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'office',
                'verbose_name_plural': 'offices',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='SaunaRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'sauna room',
                'verbose_name_plural': 'sauna rooms',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='SpaRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'spa room',
                'verbose_name_plural': 'spa rooms',
            },
            bases=('buildings.room',),
        ),
        migrations.CreateModel(
            name='WC',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildings.room')),
            ],
            options={
                'verbose_name': 'WC',
                'verbose_name_plural': 'WCs',
            },
            bases=('buildings.room',),
        ),
    ]
