# Generated by Django 5.0.12 on 2025-05-20 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
        ('organizations', '0049_organizationaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='caterer',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caterers', to='organizations.organization', verbose_name='organization'),
        ),
    ]
