# Generated by Django 5.0.12 on 2025-05-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_allergen_menu_alter_caterer_options_breakfastmenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ingredients_text', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('categories', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('openfoodfacts_url', models.URLField(blank=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('allergens', models.ManyToManyField(blank=True, to='catering.allergen')),
                ('traces', models.ManyToManyField(blank=True, related_name='trace_products', to='catering.allergen')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='products',
            field=models.ManyToManyField(blank=True, to='catering.product'),
        ),
    ]
