# Generated by Django 5.0.12 on 2025-05-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_product_ingredient_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen',
            name='course',
        ),
        migrations.AddField(
            model_name='allergen',
            name='severity',
            field=models.CharField(blank=True, choices=[('LOW', 'low'), ('MODERATE', 'moderate'), ('HIGH', 'high')], default='MODERATE', help_text='who do we need to inform', max_length=50, verbose_name='inform'),
        ),
    ]
