# Generated by Django 5.0.12 on 2025-05-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0005_remove_allergen_course_allergen_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
