# Generated by Django 5.0.12 on 2025-05-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0007_alter_allergen_name_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_synced',
            field=models.DateTimeField(),
        ),
    ]
