# Generated by Django 5.0.12 on 2025-05-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0008_alter_product_last_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
