# Generated by Django 5.0.12 on 2025-05-20 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0009_alter_product_last_synced'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchMenu',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catering.menu')),
                ('special_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'lunch menu',
                'verbose_name_plural': 'lunch menus',
            },
            bases=('catering.menu',),
        ),
    ]
