# Generated by Django 5.0.12 on 2025-05-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0010_lunchmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CateringMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='catering.catering')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caterings', to='catering.menu')),
            ],
            options={
                'verbose_name': 'catering menu',
                'verbose_name_plural': 'catering menus',
            },
        ),
        migrations.CreateModel(
            name='CateringProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catering.catering')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caterings', to='catering.product')),
            ],
            options={
                'verbose_name': 'catering product',
                'verbose_name_plural': 'catering products',
            },
        ),
    ]
