# Generated by Django 5.0.12 on 2025-05-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0011_catering_cateringmenu_cateringproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
            },
        ),
        migrations.AlterModelOptions(
            name='catering',
            options={'verbose_name': 'catering', 'verbose_name_plural': 'caterings'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('STARTER', 'starter'), ('MAIN', 'main'), ('DESSERT', 'dessert'), ('DRINK', 'drink'), ('SOUP', 'soup'), ('APPETIZER', 'appetizer')], default='', help_text='who do we need to inform', max_length=50, verbose_name='course type'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='catering.RecipeIngredient', to='catering.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CateringDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='catering.catering')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caterings', to='catering.dish')),
            ],
            options={
                'verbose_name': 'catering dish',
                'verbose_name_plural': 'catering dishes',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='catering.dish'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='catering.dish'),
        ),
    ]
