# Generated by Django 5.0.12 on 2025-05-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0012_dish_alter_catering_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='caterer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='catering.caterer'),
        ),
    ]
