# Generated by Django 5.0.12 on 2025-05-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0013_dish_caterer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('AMUSE_BOUCHE', 'amuse-bouche'), ('STARTER', 'starter'), ('SOUP', 'soup'), ('SALAD', 'salad'), ('FISH', 'fish'), ('MAIN', 'main'), ('CHEESE', 'cheese'), ('DESSERT', 'dessert'), ('DRINK', 'drink'), ('DIGESTIF', 'digestif'), ('OTHER', 'other'), ('APPETIZER', 'appetizer')], default='', help_text='who do we need to inform', max_length=50, verbose_name='course type'),
        ),
    ]
