# Generated by Django 5.0.12 on 2025-05-21 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0016_dishimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='caterer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='catering.caterer'),
        ),
    ]
