# Generated by Django 5.0.12 on 2025-05-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0017_alter_dish_caterer'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
