# Generated by Django 5.0.12 on 2025-05-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0019_product_card_description_product_card_image_and_more'),
        ('files', '0006_basefile_checksum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='files.imagefile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catering.product')),
            ],
            options={
                'verbose_name': 'dish image',
                'verbose_name_plural': 'dish images',
            },
        ),
    ]
