# Generated by Django 5.0.12 on 2025-05-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0020_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('name', 'caterer')},
        ),
    ]
