# Generated by Django 5.0.12 on 2025-03-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
