# Generated by Django 5.0.12 on 2025-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='seen_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
