# Generated by Django 5.0.12 on 2025-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr-fr', 'French'), ('nl', 'Dutch')], default='', max_length=50),
        ),
    ]
