# Generated by Django 5.0.12 on 2025-03-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('resengo_import_ready', 'Resengo import ready'), ('resengo_import_failed', 'Resengo import failed'), ('unknown', 'unknown')], default='unknown', max_length=50),
        ),
    ]
