# Generated by Django 5.0.12 on 2025-03-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_notification_dismissed_on_notification_result_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_on'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('resengo_import_ready', 'Resengo import ready'), ('organization_confirmed_event_reservation', 'organization confirmed event reservation'), ('unknown', 'unknown')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='result',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'success'), ('FAILED', 'failed'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=50),
        ),
    ]
