# Generated by Django 5.0.12 on 2025-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_alter_notification_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='language',
            field=models.CharField(blank=True, choices=[('en', '%s - %s'), ('nl', '%s - %s'), ('fr', '%s - %s'), ('de', '%s - %s'), ('es', '%s - %s'), ('it', '%s - %s')], default='', max_length=50),
        ),
    ]
