# Generated by Django 5.0.12 on 2025-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_alter_notification_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('nl', 'Nederlands'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50),
        ),
    ]
