# Generated by Django 5.0.12 on 2025-03-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0017_alter_notification_message'),
        ('organizations', '0020_organizationemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='send_to_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label__in': ['organizations', 'users'], 'model__in': ['organization', 'user']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_to_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sending_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='result',
            field=models.CharField(blank=True, choices=[('CREATED', 'created'), ('SENT', 'sent'), ('DISMISSED', 'dismissed'), ('MODIFIED', 'modified'), ('READ', 'read'), ('SEEN', 'seen'), ('error', 'error'), ('SUCCESS', 'success'), ('FAILED', 'failed'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=50),
        ),
    ]
