# Generated by Django 5.0.12 on 2025-03-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_remove_notification_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content_type',
            new_name='about_content_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='object_id',
            new_name='about_object_id',
        ),
    ]
