# Generated by Django 5.0.12 on 2025-03-21 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_alter_notification_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('html_body', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_notifications', to='notifications.notification')),
            ],
            options={
                'get_latest_by': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebPushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('nl', 'Nederlands'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('icon_url', models.URLField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webpush_notifications', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpush_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['created_on'],
                'abstract': False,
            },
        ),
    ]
