# Generated by Django 5.0.12 on 2025-03-21 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_mailnotification_webpushnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='send_to_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='send_to_object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='to',
            field=models.CharField(blank=True, choices=[('USER', 'user'), ('FULL_ORGANIZATION', 'full organization'), ('ORGANIZATION_OWNERS', 'organization owners'), ('ORGANIZATION_EMPLOYEES', 'organization employees'), ('ORGANIZATION_SUPPLIERS', 'organization suppliers'), ('ORGANIZATION_CUSTOMERS', 'organization customers')], default='USER', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
