# Generated by Django 5.0.12 on 2025-03-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_remove_notification_send_to_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
