# Generated by Django 5.0.12 on 2025-03-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0023_notification_sent_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
