# Generated by Django 5.0.12 on 2025-03-21 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0024_notification_send_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailnotification',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('nl', 'Nederlands'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mailnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to',
            field=models.CharField(blank=True, choices=[('SINGLE_USER', 'single user'), ('FULL_ORGANIZATION', 'full organization'), ('ORGANIZATION_OWNERS', 'organization owners'), ('ORGANIZATION_EMPLOYEES', 'organization employees'), ('ORGANIZATION_SUPPLIERS', 'organization suppliers'), ('ORGANIZATION_CUSTOMERS', 'organization customers')], default='SINGLE_USER', max_length=50),
        ),
    ]
