# Generated by Django 5.0.12 on 2025-03-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0027_alter_notification_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailnotification',
            name='language',
            field=models.CharField(blank=True, choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='language',
            field=models.CharField(blank=True, choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='webpushnotification',
            name='language',
            field=models.CharField(blank=True, choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50),
        ),
    ]
