# Generated by Django 5.0.12 on 2025-04-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0028_alter_mailnotification_language_and_more'),
        ('reservations', '0055_remove_reservationupdate_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='about_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sending_organization',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='webpushnotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='webpushnotification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='webpushnotification',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='webpushnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='MailNotification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
        migrations.DeleteModel(
            name='WebPushNotification',
        ),
    ]
