# Generated by Django 5.0.12 on 2025-04-16 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0029_remove_notification_about_content_type_and_more'),
        ('organizations', '0027_alter_organizationcustomer_b2b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('public_key', models.UUIDField(editable=False, null=True, unique=True)),
                ('language', models.CharField(blank=True, choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('send_on', models.DateTimeField(blank=True, null=True)),
                ('sent_on', models.DateTimeField(blank=True, null=True)),
                ('seen_on', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('dismissed_on', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(blank=True, choices=[('resengo_import_ready', 'Resengo import ready'), ('organization_confirmed_event_reservation', 'organization confirmed event reservation'), ('unknown', 'unknown')], default='unknown', max_length=50)),
                ('about_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('CREATED', 'created'), ('SENT', 'sent'), ('DISMISSED', 'dismissed'), ('MODIFIED', 'modified'), ('READ', 'read'), ('SEEN', 'seen'), ('CONFIRMED', 'confirmed'), ('CANCELED', 'canceled'), ('COMPLETED', 'completed'), ('error', 'error'), ('SUCCESS', 'success'), ('FAILED', 'failed'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=50)),
                ('about_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('sending_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('to', models.CharField(blank=True, choices=[('FULL_ORGANIZATION', 'full organization'), ('ORGANIZATION_OWNERS', 'organization owners'), ('ORGANIZATION_EMPLOYEES', 'organization employees'), ('ORGANIZATION_SUPPLIERS', 'organization suppliers'), ('ORGANIZATION_CUSTOMERS', 'organization customers')], default='', max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.notification',),
        ),
        migrations.CreateModel(
            name='MailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('html_body', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_notifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_notifications', to='notifications.notification')),
            ],
            options={
                'get_latest_by': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('disabled_all_notifications_on', models.DateTimeField(null=True)),
                ('disabled_webpush_notifications_on', models.DateTimeField(null=True)),
                ('disabled_email_notifications_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebPushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('icon_url', models.URLField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webpush_notifications', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpush_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.notification',),
        ),
    ]
