# Generated by Django 5.0.12 on 2025-04-16 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0030_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushnotification',
            name='notification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webpush_notifications', to='notifications.notification'),
        ),
    ]
