# Generated by Django 5.0.12 on 2025-04-16 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0031_alter_webpushnotification_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailnotification',
            name='notification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_notification', to='notifications.notification'),
        ),
        migrations.AlterField(
            model_name='webpushnotification',
            name='notification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webpush_notification', to='notifications.notification'),
        ),
    ]
