# Generated by Django 5.0.12 on 2025-04-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0032_alter_mailnotification_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='email_only_during_working_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='webpush_only_during_working_hours',
            field=models.BooleanField(default=False),
        ),
    ]
