# Generated by Django 5.0.12 on 2025-04-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0035_alter_usernotificationsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_in_amount',
            field=models.IntegerField(default=0),
        ),
    ]
