# Generated by Django 5.0.12 on 2025-04-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0036_alter_notification_send_in_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='celery_task_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_in_interval',
            field=models.CharField(choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hour'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], default='seconds', max_length=50),
        ),
    ]
