# Generated by Django 5.0.12 on 2025-04-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0037_notification_celery_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='celery_task_id',
        ),
    ]
