# Generated by Django 5.0.12 on 2025-04-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0038_remove_notification_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_to',
            field=models.URLField(blank=True, default=''),
        ),
    ]
