# Generated by Django 5.0.12 on 2025-04-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0039_notification_redirect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
