# Generated by Django 5.0.12 on 2025-04-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0040_notification_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='redirect_to',
        ),
        migrations.AddField(
            model_name='notification',
            name='button_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
