# Generated by Django 5.0.12 on 2025-04-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0041_remove_notification_redirect_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailnotification',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mailnotification',
            name='language',
        ),
    ]
