# Generated by Django 5.0.12 on 2025-04-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0043_remove_webpushnotification_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpushnotification',
            name='url',
        ),
        migrations.AddField(
            model_name='webpushnotification',
            name='open_notification_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
