# Generated by Django 5.0.12 on 2025-04-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0044_remove_webpushnotification_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='celery_task_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
