# Generated by Django 5.0.12 on 2025-04-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0045_notification_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailnotification',
            name='bcc_email_addresses',
            field=models.TextField(blank=True, default='', help_text="Use a comma ',' as the separator"),
        ),
        migrations.AddField(
            model_name='mailnotification',
            name='cc_email_addresses',
            field=models.TextField(blank=True, default='', help_text="Use a comma ',' as the separator"),
        ),
        migrations.AddField(
            model_name='mailnotification',
            name='to_email_addresses',
            field=models.TextField(default='', help_text="Use a comma ',' as the separator"),
        ),
    ]
