# Generated by Django 5.0.12 on 2025-04-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0047_alter_usernotification_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='language',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='language',
            field=models.CharField(blank=True, choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50),
        ),
    ]
