# Generated by Django 5.0.12 on 2025-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0048_remove_notification_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsettings',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sent on'),
        ),
    ]
