# Generated by Django 5.0.12 on 2025-04-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0050_alter_mailnotification_modified_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpushnotification',
            old_name='open_notification_url',
            new_name='show_notification_url',
        ),
    ]
