# Generated by Django 5.0.12 on 2025-04-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0052_notification_redirect_to_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
