# Generated by Django 5.0.12 on 2025-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0055_alter_notification_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='redirect_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
