# Generated by Django 5.0.12 on 2025-02-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_buffet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodConcept',
            fields=[
                ('concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.concept')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.concept',),
        ),
        migrations.CreateModel(
            name='SingleEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('show_in_ongoing_events', models.BooleanField(default=True)),
                ('starting_at', models.DateTimeField(null=True)),
                ('ending_on', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='Buffet',
        ),
    ]
