# Generated by Django 5.0.12 on 2025-02-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_concept_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='Brunch',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='DinnerAndDance',
            fields=[
                ('concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.concept')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.concept',),
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('concept_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.concept')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.concept',),
        ),
        migrations.DeleteModel(
            name='FoodConcept',
        ),
    ]
