# Generated by Django 5.0.12 on 2025-02-07 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_brunchconcept_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'break event',
                'verbose_name_plural': 'break events',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='BrunchEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'brunch event',
                'verbose_name_plural': 'brunch events',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='CeremonyEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'ceremony event',
                'verbose_name_plural': 'ceremony events',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='ClosingEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'closing event',
                'verbose_name_plural': 'closing events',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='DanceEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'dance event',
                'verbose_name_plural': 'dance events',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='DinnerEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'dinner event',
                'verbose_name_plural': 'dinner events',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='ReceptionEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'reception event',
                'verbose_name_plural': 'reception events',
            },
            bases=('events.singleevent',),
        ),
        migrations.RemoveField(
            model_name='brunch',
            name='singleevent_ptr',
        ),
        migrations.RemoveField(
            model_name='ceremony',
            name='singleevent_ptr',
        ),
        migrations.RemoveField(
            model_name='closing',
            name='singleevent_ptr',
        ),
        migrations.RemoveField(
            model_name='dance',
            name='singleevent_ptr',
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='singleevent_ptr',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='singleevent_ptr',
        ),
        migrations.AlterModelOptions(
            name='singleevent',
            options={'verbose_name': 'single event', 'verbose_name_plural': 'single events'},
        ),
        migrations.DeleteModel(
            name='Break',
        ),
        migrations.DeleteModel(
            name='Brunch',
        ),
        migrations.DeleteModel(
            name='Ceremony',
        ),
        migrations.DeleteModel(
            name='Closing',
        ),
        migrations.DeleteModel(
            name='Dance',
        ),
        migrations.DeleteModel(
            name='Dinner',
        ),
        migrations.DeleteModel(
            name='Reception',
        ),
    ]
