# Generated by Django 5.0.12 on 2025-02-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_brunchconcept_default_starting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='brunchconcept',
            name='default_ending_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
