# Generated by Django 5.0.12 on 2025-02-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_reception'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receptionevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.DeleteModel(
            name='Reception',
        ),
    ]
