# Generated by Django 5.0.12 on 2025-02-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_receptionevent_options_delete_reception'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrunchEventPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
