# Generated by Django 5.0.12 on 2025-02-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_bruncheventprice_brunch_event'),
        ('payments', '0009_alter_agepricematrix_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptPriceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.concept')),
                ('price_matrix', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.pricematrix')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
