# Generated by Django 5.0.12 on 2025-02-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_receptionevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
    ]
