# Generated by Django 5.0.12 on 2025-02-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_concept_slug_event_slug'),
        ('organizations', '0006_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='organizations.organization'),
        ),
    ]
