# Generated by Django 5.0.12 on 2025-02-14 11:30

import scaleos.shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_concept_slug_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='card_image',
            field=models.ImageField(null=True, upload_to=scaleos.shared.models.CardModel.model_directory_path, verbose_name='card image'),
        ),
    ]
