# Generated by Django 5.0.12 on 2025-02-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_concept_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='card_description',
            field=models.TextField(default='', verbose_name='card description'),
        ),
    ]
