# Generated by Django 5.0.12 on 2025-02-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_concept_card_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
