# Generated by Django 5.0.12 on 2025-02-15 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptpricematrix',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.concept'),
        ),
    ]
