# Generated by Django 5.0.12 on 2025-02-15 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_conceptpricematrix_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptpricematrix',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_matrixes', to='events.concept'),
        ),
    ]
