# Generated by Django 5.0.12 on 2025-03-13 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_concept_card_description_and_more'),
        ('reservations', '0030_eventreservationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='reservation_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.eventreservationsettings'),
        ),
    ]
