# Generated by Django 5.0.12 on 2025-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_concept_reservation_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='name'),
        ),
    ]
