# Generated by Django 5.0.12 on 2025-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_event_reservation_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_reservations',
            field=models.BooleanField(default=True),
        ),
    ]
