# Generated by Django 5.0.12 on 2025-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_event_allow_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='concept',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='concept',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='concept',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
    ]
