# Generated by Django 5.0.12 on 2025-03-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_concept_name_de_concept_name_en_concept_name_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinneranddanceconcept',
            name='concept_ptr',
        ),
        migrations.RemoveField(
            model_name='weddingconcept',
            name='concept_ptr',
        ),
        migrations.DeleteModel(
            name='BrunchConcept',
        ),
        migrations.DeleteModel(
            name='DinnerAndDanceConcept',
        ),
        migrations.DeleteModel(
            name='WeddingConcept',
        ),
    ]
