# Generated by Django 5.0.12 on 2025-03-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_remove_dinneranddanceconcept_concept_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='polymorphic_ctype',
        ),
    ]
