# Generated by Django 5.0.12 on 2025-03-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_remove_concept_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='card_description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='concept',
            name='card_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='concept',
            name='card_description_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='concept',
            name='card_description_nl',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
    ]
