# Generated by Django 5.0.12 on 2025-03-24 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0040_customerconcept'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='CustomerConcept',
        ),
    ]
