# Generated by Django 5.0.12 on 2025-03-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_customerconcept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerconcept',
            name='based_on_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='events.concept'),
        ),
    ]
