# Generated by Django 5.0.12 on 2025-03-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_alter_customerconcept_based_on_concept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrunchEventPrice',
        ),
    ]
