# Generated by Django 5.0.12 on 2025-03-24 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_delete_bruncheventprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDuplicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('every_interval', models.CharField(choices=[('EVERY_DAY', 'every day'), ('EVERY_WEEK', 'every week'), ('EVERY_MONTH', 'every month'), ('EVERY_YEAR', 'every year')], default='EVERY_WEEK', max_length=50, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.singleevent')),
            ],
        ),
    ]
