# Generated by Django 5.0.12 on 2025-03-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_eventduplicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventduplicator',
            name='amount',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
