# Generated by Django 5.0.12 on 2025-03-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_eventduplicator_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventduplicator',
            old_name='from_date',
            new_name='from_date_time',
        ),
        migrations.RenameField(
            model_name='eventduplicator',
            old_name='to_date',
            new_name='to_date_time',
        ),
        migrations.AlterField(
            model_name='eventduplicator',
            name='every_interval',
            field=models.CharField(choices=[('EVERY_DAY', 'every AMOUNT day'), ('EVERY_WEEK', 'every AMOUNT week'), ('EVERY_MONTH', 'every AMOUNT month'), ('EVERY_YEAR', 'every AMOUNT year')], default='EVERY_WEEK', max_length=50, null=True),
        ),
    ]
