# Generated by Django 5.0.12 on 2025-03-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_rename_from_date_eventduplicator_from_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleevent',
            name='duplicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventduplicator'),
        ),
    ]
