# Generated by Django 5.0.12 on 2025-03-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_singleevent_duplicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventduplicator',
            name='from_date_time',
        ),
        migrations.RemoveField(
            model_name='eventduplicator',
            name='to_date_time',
        ),
        migrations.AddField(
            model_name='eventduplicator',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eventduplicator',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
