# Generated by Django 5.0.12 on 2025-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_remove_eventduplicator_from_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='segment',
            field=models.CharField(choices=[('B2B', 'b2b'), ('B2C', 'b2c'), ('BOTH', 'both')], default='BOTH', max_length=50, null=True),
        ),
    ]
