# Generated by Django 5.0.12 on 2025-03-25 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0050_concept_segment'),
        ('hr', '0015_alter_person_mother_tongue'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.UUIDField(editable=False, null=True, unique=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='checked in at')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='checked out at')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.singleevent', verbose_name='event')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr.person', verbose_name='person')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
