# Generated by Django 5.0.12 on 2025-03-25 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_eventguest'),
        ('organizations', '0020_organizationemployee'),
        ('payments', '0044_remove_pricematrixitem_name_es_and_more'),
        ('reservations', '0041_reservation_on_waitinglist_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='organizations.organization', verbose_name='organizer'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='reservation_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.eventreservationsettings', verbose_name='reservation settings'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='segment',
            field=models.CharField(choices=[('B2B', 'b2b'), ('B2C', 'b2c'), ('BOTH', 'both')], default='BOTH', max_length=50, null=True, verbose_name='segment'),
        ),
        migrations.AlterField(
            model_name='conceptpricematrix',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_matrixes', to='events.concept', verbose_name='concept'),
        ),
        migrations.AlterField(
            model_name='conceptpricematrix',
            name='price_matrix',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.pricematrix', verbose_name='price matrix'),
        ),
        migrations.AlterField(
            model_name='conceptpricematrix',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='valid from'),
        ),
        migrations.AlterField(
            model_name='conceptpricematrix',
            name='valid_till',
            field=models.DateTimeField(blank=True, null=True, verbose_name='valid till'),
        ),
        migrations.AlterField(
            model_name='customerconcept',
            name='based_on_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='events.concept', verbose_name='based on concept'),
        ),
        migrations.AlterField(
            model_name='customerconcept',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='organizations.organizationcustomer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='allow_reservations',
            field=models.BooleanField(default=True, verbose_name='allow reservations'),
        ),
        migrations.AlterField(
            model_name='event',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.concept', verbose_name='concept'),
        ),
        migrations.AlterField(
            model_name='event',
            name='expected_number_of_guests',
            field=models.IntegerField(blank=True, null=True, verbose_name='expected number of guests'),
        ),
        migrations.AlterField(
            model_name='event',
            name='maximum_number_of_guests',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum number of guests'),
        ),
        migrations.AlterField(
            model_name='event',
            name='minimum_number_of_guests',
            field=models.IntegerField(blank=True, null=True, verbose_name='minimum number of guests'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reservation_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.eventreservationsettings', verbose_name='reservation settings'),
        ),
        migrations.AlterField(
            model_name='eventduplicator',
            name='amount',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='eventduplicator',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.singleevent', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventduplicator',
            name='every_interval',
            field=models.CharField(choices=[('EVERY_DAY', 'every AMOUNT day'), ('EVERY_WEEK', 'every AMOUNT week'), ('EVERY_MONTH', 'every AMOUNT month'), ('EVERY_YEAR', 'every AMOUNT year')], default='EVERY_WEEK', max_length=50, null=True, verbose_name='every interval'),
        ),
        migrations.AlterField(
            model_name='eventduplicator',
            name='from_date',
            field=models.DateField(null=True, verbose_name='from date'),
        ),
        migrations.AlterField(
            model_name='eventduplicator',
            name='to_date',
            field=models.DateField(null=True, verbose_name='to date'),
        ),
        migrations.AlterField(
            model_name='singleevent',
            name='duplicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventduplicator', verbose_name='duplicator'),
        ),
        migrations.AlterField(
            model_name='singleevent',
            name='ending_on',
            field=models.DateTimeField(null=True, verbose_name='ending on'),
        ),
        migrations.AlterField(
            model_name='singleevent',
            name='show_in_ongoing_events',
            field=models.BooleanField(default=True, verbose_name='show in ongoing events'),
        ),
        migrations.AlterField(
            model_name='singleevent',
            name='starting_at',
            field=models.DateTimeField(null=True, verbose_name='starting at'),
        ),
    ]
