# Generated by Django 5.0.12 on 2025-03-25 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_alter_concept_organizer_and_more'),
        ('geography', '0007_room_floor_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='event')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.floor', verbose_name='floor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
