# Generated by Django 5.0.12 on 2025-03-25 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_eventfloor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORGANIZER', 'organizer'), ('STAFF', 'staff'), ('VIP', 'vip'), ('BRIDE', 'bride'), ('GROOM', 'groom'), ('DJ', 'dj'), ('ARTIST', 'artist')], max_length=50, null=True, verbose_name='role')),
                ('event_guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventguest', verbose_name='event guest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
