# Generated by Django 5.0.12 on 2025-03-26 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_guestrole'),
        ('organizations', '0020_organizationemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'birthday event',
                'verbose_name_plural': 'birthday events',
            },
            bases=('events.singleevent',),
        ),
        migrations.AlterModelOptions(
            name='guestrole',
            options={'verbose_name': 'guest role', 'verbose_name_plural': 'guest roles'},
        ),
        migrations.AddField(
            model_name='guestrole',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='guestrole',
            name='from_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='from organization'),
        ),
        migrations.AlterField(
            model_name='guestrole',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'organizer'), ('STAFF', 'staff'), ('VIP', 'vip'), ('BRIDE', 'bride'), ('GROOM', 'groom'), ('BIRTHDAY_PERSON', 'birthday person'), ('DJ', 'dj'), ('ARTIST', 'artist'), ('PHOTOGRAPHER', 'photographer'), ('TECHNICIAN', 'technician'), ('COOK', 'cook'), ('CATERER', 'caterer'), ('SPEAKER', 'speaker'), ('OTHER', 'other')], max_length=50, null=True, verbose_name='role'),
        ),
    ]
