# Generated by Django 5.0.12 on 2025-03-26 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_alter_eventguest_person'),
        ('hr', '0019_remove_person_primary_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventguest',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr.person', verbose_name='person'),
        ),
    ]
