# Generated by Django 5.0.12 on 2025-03-26 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_alter_eventguest_person'),
        ('organizations', '0020_organizationemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestrole',
            name='from_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='from organization'),
        ),
    ]
