# Generated by Django 5.0.12 on 2025-03-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_alter_guestrole_from_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerconcept',
            name='google_fotos_album',
            field=models.URLField(blank=True, null=True, verbose_name='google fotos album'),
        ),
    ]
