# Generated by Django 5.0.12 on 2025-03-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_customerconcept_google_fotos_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'wedding',
                'verbose_name_plural': 'weddings',
            },
            bases=('events.singleevent',),
        ),
        migrations.AlterModelOptions(
            name='birthdayevent',
            options={'verbose_name': 'birthday', 'verbose_name_plural': 'birthdays'},
        ),
    ]
