# Generated by Django 5.0.12 on 2025-03-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_weddingevent_alter_birthdayevent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBuildingEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'team building',
                'verbose_name_plural': 'team buildings',
            },
            bases=('events.singleevent',),
        ),
        migrations.AlterModelOptions(
            name='brunchevent',
            options={'verbose_name': 'brunch', 'verbose_name_plural': 'brunches'},
        ),
    ]
