# Generated by Django 5.0.12 on 2025-03-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_teambuildingevent_alter_brunchevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakevent',
            options={'verbose_name': 'break', 'verbose_name_plural': 'breaks'},
        ),
        migrations.AlterModelOptions(
            name='closingevent',
            options={'verbose_name': 'closing', 'verbose_name_plural': 'closings'},
        ),
        migrations.AlterModelOptions(
            name='dinnerevent',
            options={'verbose_name': 'dinner', 'verbose_name_plural': 'dinners'},
        ),
        migrations.AlterModelOptions(
            name='receptionevent',
            options={'verbose_name': 'reception', 'verbose_name_plural': 'receptions'},
        ),
    ]
