# Generated by Django 5.0.12 on 2025-03-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0062_alter_breakevent_options_alter_closingevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'presentation',
                'verbose_name_plural': 'presentations',
            },
            bases=('events.singleevent',),
        ),
    ]
