# Generated by Django 5.0.12 on 2025-03-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0065_liveperformanceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'breakfast',
                'verbose_name_plural': 'breakfasts',
            },
            bases=('events.singleevent',),
        ),
        migrations.CreateModel(
            name='LunchEvent',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'lunch',
                'verbose_name_plural': 'lunches',
            },
            bases=('events.singleevent',),
        ),
    ]
