# Generated by Django 5.0.12 on 2025-03-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0066_breakfastevent_lunchevent'),
        ('hr', '0019_remove_person_primary_telephone_number'),
        ('organizations', '0020_organizationemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestrole',
            name='event_guest',
        ),
        migrations.RemoveField(
            model_name='guestrole',
            name='from_organization',
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.UUIDField(editable=False, null=True, unique=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='checked in at')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='checked out at')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.singleevent', verbose_name='event')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr.person', verbose_name='person')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AttendeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORGANIZER', 'organizer'), ('STAFF', 'staff'), ('VIP', 'vip'), ('BRIDE', 'bride'), ('GROOM', 'groom'), ('BIRTHDAY_PERSON', 'birthday person'), ('DJ', 'dj'), ('ARTIST', 'artist'), ('PHOTOGRAPHER', 'photographer'), ('TECHNICIAN', 'technician'), ('COOK', 'cook'), ('CATERER', 'caterer'), ('SPEAKER', 'speaker'), ('OTHER', 'other')], max_length=50, null=True, verbose_name='role')),
                ('comments', models.TextField(blank=True, default='', verbose_name='comments')),
                ('from_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='from organization')),
                ('event_attendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventattendee', verbose_name='event attendee')),
            ],
            options={
                'verbose_name': 'attendee role',
                'verbose_name_plural': 'attendee roles',
            },
        ),
        migrations.DeleteModel(
            name='EventGuest',
        ),
        migrations.DeleteModel(
            name='GuestRole',
        ),
    ]
