# Generated by Django 5.0.12 on 2025-03-27 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0068_event_payment_settings'),
        ('payments', '0045_alter_price_vat_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='payment_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentreservationsettings', verbose_name='payment settings'),
        ),
    ]
