# Generated by Django 5.0.12 on 2025-03-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0069_concept_payment_settings'),
        ('payments', '0047_remove_paymentreservationsettings_fixed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='prepayment_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.prepaymentreservationsettings', verbose_name='prepayment settings'),
        ),
        migrations.AddField(
            model_name='event',
            name='prepayment_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.prepaymentreservationsettings', verbose_name='prepayment settings'),
        ),
    ]
