# Generated by Django 5.0.12 on 2025-03-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0071_remove_concept_prepayment_settings_and_more'),
        ('payments', '0078_eventreservationprepaymentsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='event_reservation_prepayment_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.eventreservationprepaymentsettings', verbose_name='event reservation prepayment settings'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_reservation_prepayment_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.eventreservationprepaymentsettings', verbose_name='event reservation prepayment settings'),
        ),
    ]
