# Generated by Django 5.0.12 on 2025-03-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0072_concept_event_reservation_prepayment_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='event_reservation_prepayment_settings',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='payment_settings',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_reservation_prepayment_settings',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payment_settings',
        ),
    ]
