# Generated by Django 5.0.12 on 2025-03-30 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0073_remove_concept_event_reservation_prepayment_settings_and_more'),
        ('payments', '0080_remove_eventreservationprepaymentsettings_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='event_reservation_payment_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.eventreservationpaymentsettings', verbose_name='event reservation payment settings'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_reservation_payment_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.eventreservationpaymentsettings', verbose_name='event reservation payment settings'),
        ),
    ]
