# Generated by Django 5.0.12 on 2025-03-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0074_concept_event_reservation_payment_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='event_reservation_payment_settings',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_reservation_payment_settings',
        ),
    ]
