# Generated by Django 5.0.12 on 2025-04-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0076_concept_event_reservation_payment_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerconcept',
            options={'verbose_name': 'customer concept', 'verbose_name_plural': 'customer concepts'},
        ),
        migrations.AlterModelOptions(
            name='singleevent',
            options={'ordering': ['starting_at'], 'verbose_name': 'single event', 'verbose_name_plural': 'single events'},
        ),
    ]
