# Generated by Django 5.0.12 on 2025-04-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0078_sleepover'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayOver',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'stay over',
                'verbose_name_plural': 'stay overs',
            },
            bases=('events.singleevent',),
        ),
        migrations.DeleteModel(
            name='SleepOver',
        ),
    ]
