# Generated by Django 5.0.12 on 2025-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0079_stayover_delete_sleepover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerconcept',
            name='google_fotos_album',
            field=models.URLField(blank=True, default='', verbose_name='google fotos album'),
        ),
    ]
