# Generated by Django 5.0.12 on 2025-04-18 14:59

import scaleos.shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0080_alter_customerconcept_google_fotos_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='card_description',
            field=models.TextField(blank=True, default='', verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='event',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to=scaleos.shared.models.CardModel.model_directory_path, verbose_name='card image'),
        ),
    ]
