# Generated by Django 5.0.12 on 2025-04-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0081_event_card_description_event_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='card_description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='event',
            name='card_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='event',
            name='card_description_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='event',
            name='card_description_nl',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
    ]
