# Generated by Django 5.0.12 on 2025-04-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0082_event_card_description_de_event_card_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeerole',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'organizer'), ('STAFF', 'staff'), ('VIP', 'vip'), ('BRIDE', 'bride'), ('GROOM', 'groom'), ('BIRTHDAY_PERSON', 'birthday person'), ('WEDDING_ANNIVERSARY', 'wedding anniversary'), ('DJ', 'dj'), ('ARTIST', 'artist'), ('PHOTOGRAPHER', 'photographer'), ('TECHNICIAN', 'technician'), ('COOK', 'cook'), ('CATERER', 'caterer'), ('SPEAKER', 'speaker'), ('OTHER', 'other')], max_length=50, null=True, verbose_name='role'),
        ),
    ]
