# Generated by Django 5.0.12 on 2025-04-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0083_alter_attendeerole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeerole',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'organizer'), ('STAFF', 'staff'), ('VIP', 'vip'), ('BRIDE', 'bride'), ('GROOM', 'groom'), ('BIRTHDAY_PERSON', 'birthday person'), ('WEDDING_ANNIVERSARY', 'wedding anniversary'), ('DJ', 'dj'), ('ARTIST', 'artist'), ('PHOTOGRAPHER', 'photographer'), ('TECHNICIAN', 'technician'), ('COOK', 'cook'), ('CATERER', 'caterer'), ('SPEAKER', 'speaker'), ('OTHER', 'other')], default='', max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='segment',
            field=models.CharField(choices=[('B2B', 'b2b'), ('B2C', 'b2c'), ('BOTH', 'both')], default='BOTH', max_length=50, verbose_name='segment'),
        ),
        migrations.AlterField(
            model_name='eventduplicator',
            name='every_interval',
            field=models.CharField(choices=[('EVERY_DAY', 'every AMOUNT day'), ('EVERY_WEEK', 'every AMOUNT week'), ('EVERY_MONTH', 'every AMOUNT month'), ('EVERY_YEAR', 'every AMOUNT year')], default='EVERY_WEEK', max_length=50, verbose_name='every interval'),
        ),
    ]
