# Generated by Django 5.0.12 on 2025-04-22 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0085_eventupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMessage',
            fields=[
                ('eventupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.eventupdate')),
                ('message', models.TextField(default='', verbose_name='message')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.eventupdate',),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
    ]
