# Generated by Django 5.0.12 on 2025-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0086_eventmessage_eventupdate_send_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventupdate',
            name='send_notification',
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='inform',
            field=models.CharField(choices=[('NOBODY', 'nobody'), ('ALL_GUESTS', 'all guests'), ('ALL_RESERVATION_REQUESTERS', 'all reservation requesters')], default='NOBODY', max_length=50, verbose_name='segment'),
        ),
    ]
