# Generated by Django 5.0.12 on 2025-04-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0087_remove_eventupdate_send_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventupdate',
            name='visible_from',
            field=models.DateTimeField(null=True, verbose_name='visible from'),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='visible_till',
            field=models.DateTimeField(null=True, verbose_name='visible till'),
        ),
        migrations.AlterField(
            model_name='eventupdate',
            name='inform',
            field=models.CharField(choices=[('NOBODY', 'nobody'), ('ALL_GUESTS', 'all guests'), ('ALL_RESERVATION_REQUESTERS', 'all reservation requesters'), ('ORGANIZER', 'organizer'), ('STAFF', 'staff'), ('VIP', 'vip'), ('BRIDE', 'bride'), ('GROOM', 'groom'), ('BIRTHDAY_PERSON', 'birthday person'), ('WEDDING_ANNIVERSARY', 'wedding anniversary'), ('DJ', 'dj'), ('ARTIST', 'artist'), ('PHOTOGRAPHER', 'photographer'), ('TECHNICIAN', 'technician'), ('COOK', 'cook'), ('CATERER', 'caterer'), ('SPEAKER', 'speaker'), ('OTHER', 'other')], default='NOBODY', help_text='who do we need to inform', max_length=50, verbose_name='inform'),
        ),
    ]
