# Generated by Django 5.0.12 on 2025-04-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0088_eventupdate_visible_from_eventupdate_visible_till_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventupdate',
            name='visible_from',
        ),
        migrations.RemoveField(
            model_name='eventupdate',
            name='visible_till',
        ),
        migrations.AddField(
            model_name='eventmessage',
            name='visible_from',
            field=models.DateTimeField(null=True, verbose_name='visible from'),
        ),
        migrations.AddField(
            model_name='eventmessage',
            name='visible_till',
            field=models.DateTimeField(null=True, verbose_name='visible till'),
        ),
    ]
