# Generated by Django 5.0.12 on 2025-04-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0089_remove_eventupdate_visible_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reserved_spots',
            field=models.IntegerField(default=0, verbose_name='reserved spots'),
        ),
    ]
