# Generated by Django 5.0.12 on 2025-04-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0090_event_reserved_spots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerconcept',
            name='customer',
        ),
    ]
