# Generated by Django 5.0.12 on 2025-04-24 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0092_alter_customerconcept_modified_by_and_more'),
        ('organizations', '0041_alter_organizationemployee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerconcept',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='organizations.organizationcustomer', verbose_name='customer'),
        ),
    ]
