# Generated by Django 5.0.12 on 2025-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0093_customerconcept_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmessage',
            name='title',
            field=models.TextField(default='', verbose_name='title'),
        ),
    ]
