# Generated by Django 5.0.12 on 2025-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0094_eventmessage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmessage',
            name='title',
            field=models.CharField(default='', verbose_name='title'),
        ),
    ]
