# Generated by Django 5.0.12 on 2025-04-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0095_alter_eventmessage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='reservation_settings',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reservation_settings',
        ),
    ]
