# Generated by Django 5.0.12 on 2025-04-25 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0096_remove_concept_reservation_settings_and_more'),
        ('reservations', '0070_reservationsettings_eventreservationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='reservation_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.eventreservationsettings', verbose_name='reservation settings'),
        ),
        migrations.AddField(
            model_name='event',
            name='reservation_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.eventreservationsettings', verbose_name='reservation settings'),
        ),
    ]
