# Generated by Django 5.0.12 on 2025-05-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0097_concept_reservation_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reserved_spots',
            field=models.IntegerField(blank=True, default=0, verbose_name='reserved spots'),
        ),
    ]
