# Generated by Django 5.0.12 on 2025-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0098_alter_event_reserved_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='slogan',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='slogan'),
        ),
    ]
