# Generated by Django 5.0.12 on 2025-05-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0101_concept_transition_concept_transition_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='transition_durtion',
            field=models.IntegerField(default=1500, help_text='in milliseconds', verbose_name='transition duration'),
        ),
        migrations.AddField(
            model_name='event',
            name='transition_durtion',
            field=models.IntegerField(default=1500, help_text='in milliseconds', verbose_name='transition duration'),
        ),
    ]
