# Generated by Django 5.0.12 on 2025-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0103_rename_transition_durtion_concept_transition_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeerole',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'organizer'), ('STAFF', 'staff'), ('VIP', 'vip'), ('BRIDE', 'bride'), ('GROOM', 'groom'), ('BIRTHDAY_PERSON', 'birthday person'), ('WEDDING_ANNIVERSARY', 'wedding anniversary'), ('DJ', 'dj'), ('ARTIST', 'artist'), ('PHOTOGRAPHER', 'photographer'), ('TECHNICIAN', 'technician'), ('COOK', 'cook'), ('CATERER', 'caterer'), ('SPEAKER', 'speaker'), ('SECURITY_GUARD', 'security guard'), ('STEWARD', 'steward'), ('PARKING_ASSISTANT', 'parking assistant'), ('OTHER', 'other')], default='', max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='eventmessage',
            name='visible_till',
            field=models.DateTimeField(blank=True, null=True, verbose_name='visible till'),
        ),
        migrations.AlterField(
            model_name='eventupdate',
            name='inform',
            field=models.CharField(choices=[('NOBODY', 'nobody'), ('ALL_GUESTS', 'all guests'), ('ALL_RESERVATION_REQUESTERS', 'all reservation requesters'), ('ORGANIZER', 'organizer'), ('STAFF', 'staff'), ('VIP', 'vip'), ('BRIDE', 'bride'), ('GROOM', 'groom'), ('BIRTHDAY_PERSON', 'birthday person'), ('WEDDING_ANNIVERSARY', 'wedding anniversary'), ('DJ', 'dj'), ('ARTIST', 'artist'), ('PHOTOGRAPHER', 'photographer'), ('TECHNICIAN', 'technician'), ('COOK', 'cook'), ('CATERER', 'caterer'), ('SPEAKER', 'speaker'), ('SECURITY_GUARD', 'security guard'), ('STEWARD', 'steward'), ('PARKING_ASSISTANT', 'parking assistant'), ('OTHER', 'other')], default='NOBODY', help_text='who do we need to inform', max_length=50, verbose_name='inform'),
        ),
    ]
