# Generated by Django 5.0.12 on 2025-05-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0104_alter_attendeerole_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='events.singleevent', verbose_name='parent'),
        ),
    ]
