# Generated by Django 5.0.12 on 2025-05-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0105_singleevent_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMix',
            fields=[
                ('singleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.singleevent')),
            ],
            options={
                'verbose_name': 'mix of events',
                'verbose_name_plural': 'mix of events',
            },
            bases=('events.singleevent',),
        ),
        migrations.RemoveField(
            model_name='singleevent',
            name='parent',
        ),
    ]
