# Generated by Django 5.0.12 on 2025-05-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0011_catering_cateringmenu_cateringproduct'),
        ('events', '0107_singleevent_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleevent',
            name='catering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catering.catering', verbose_name='catering'),
        ),
    ]
