# Generated by Django 5.0.12 on 2025-05-21 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0017_alter_dish_caterer'),
        ('events', '0108_singleevent_catering'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='catering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catering.catering', verbose_name='catering'),
        ),
    ]
