# Generated by Django 5.0.12 on 2025-06-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0109_concept_catering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerconcept',
            name='customer',
        ),
    ]
