# Generated by Django 5.0.12 on 2025-06-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0110_remove_customerconcept_customer'),
        ('organizations', '0052_customer_b2bcustomer_b2ccustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerconcept',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='organizations.customer', verbose_name='customer'),
        ),
    ]
