# Generated by Django 5.0.12 on 2025-06-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0111_customerconcept_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventduplicator',
            name='to_date',
        ),
        migrations.AddField(
            model_name='eventduplicator',
            name='events_created',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='events created'),
        ),
        migrations.AddField(
            model_name='eventduplicator',
            name='target_date',
            field=models.DateField(null=True, verbose_name='to date'),
        ),
        migrations.AlterField(
            model_name='eventduplicator',
            name='from_date',
            field=models.DateField(blank=True, editable=False, help_text='as starting date, we automatically take the starting datetime of the event', null=True, verbose_name='from date'),
        ),
    ]
