# Generated by Django 5.0.12 on 2025-06-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_remove_room_in_building_remove_room_floor_ptr_and_more'),
        ('events', '0112_remove_eventduplicator_to_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfloor',
            name='floor_layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.floorlayout', verbose_name='floor layout'),
        ),
        migrations.AlterField(
            model_name='eventfloor',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.floor', verbose_name='floor'),
        ),
    ]
