# Generated by Django 5.0.12 on 2025-02-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_brunchconcept_default_ending_time'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brunchreservation',
            name='brunch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.brunchevent'),
        ),
    ]
