# Generated by Django 5.0.12 on 2025-02-08 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_price_public_key'),
        ('reservations', '0004_alter_brunchreservation_brunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='brunchreservation',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='brunchreservation',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.agepricematrixitem'),
        ),
    ]
