# Generated by Django 5.0.12 on 2025-02-08 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_bruncheventprice_brunch_event'),
        ('payments', '0005_price_public_key'),
        ('reservations', '0005_brunchreservation_amount_brunchreservation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brunchreservation',
            name='brunch',
        ),
        migrations.RemoveField(
            model_name='brunchreservation',
            name='price',
        ),
        migrations.AddField(
            model_name='brunchreservation',
            name='age_price_matrix_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.agepricematrixitem'),
        ),
        migrations.AddField(
            model_name='brunchreservation',
            name='brunch_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='events.brunchevent'),
        ),
    ]
