# Generated by Django 5.0.12 on 2025-02-08 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_agepricematrix_agepricematrixitem'),
        ('reservations', '0007_remove_brunchreservation_age_price_matrix_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='brunchreservation',
            name='age_price_matrix_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.agepricematrixitem'),
        ),
    ]
