# Generated by Django 5.0.12 on 2025-02-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_public_key'),
        ('payments', '0014_alter_pricematrix_slug'),
        ('reservations', '0008_brunchreservation_age_price_matrix_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservation')),
                ('amount', models.IntegerField(null=True)),
                ('age_price_matrix_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.agepricematrixitem')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='events.event')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('reservations.reservation',),
        ),
        migrations.DeleteModel(
            name='BrunchReservation',
        ),
    ]
