# Generated by Django 5.0.12 on 2025-02-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_eventreservation_delete_brunchreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
