# Generated by Django 5.0.12 on 2025-02-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_agepricematrixitem_options_and_more'),
        ('reservations', '0010_reservation_created_on_reservation_modified_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreservation',
            name='age_price_matrix_item',
        ),
        migrations.RemoveField(
            model_name='eventreservation',
            name='amount',
        ),
        migrations.CreateModel(
            name='ReservationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('price_matrix_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.pricematrixitem')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
