# Generated by Django 5.0.12 on 2025-02-17 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_remove_eventreservation_age_price_matrix_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationline',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reservations.reservation'),
        ),
    ]
