# Generated by Django 5.0.12 on 2025-02-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_reservationline_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationline',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
