# Generated by Django 5.0.12 on 2025-02-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_reservationline_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
