# Generated by Django 5.0.12 on 2025-02-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_reservation_public_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationline',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
