# Generated by Django 5.0.12 on 2025-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_alter_reservationline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='finished_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
