# Generated by Django 5.0.12 on 2025-02-18 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_reservation_confirmation_mail_sent_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='confirmation_email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='email_address_confirmed_on',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='person',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
