# Generated by Django 5.0.12 on 2025-02-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_reservation_card_description_reservation_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='verified_on',
            field=models.DateTimeField(blank=True, help_text='the moment the reservation is verified by the user who made the reservation', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='finished_on',
            field=models.DateTimeField(blank=True, help_text='the moment the reservation has been made', null=True),
        ),
    ]
