# Generated by Django 5.0.12 on 2025-02-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_reservation_verified_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='verified_on',
            field=models.DateTimeField(blank=True, help_text='the moment the reservation is verified\n            by the user who made the reservation', null=True),
        ),
    ]
