# Generated by Django 5.0.12 on 2025-02-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_alter_reservation_verified_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='verified_on',
            new_name='requester_confirmed_on',
        ),
    ]
