# Generated by Django 5.0.12 on 2025-02-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_rename_verified_on_reservation_requester_confirmed_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='confirmed_on',
            new_name='organization_confirmed_on',
        ),
    ]
