# Generated by Django 5.0.12 on 2025-02-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_paymentrequest'),
        ('reservations', '0026_rename_confirmed_on_reservation_organization_confirmed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentrequest'),
        ),
    ]
