# Generated by Django 5.0.12 on 2025-03-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0029_reservation_modified_by_alter_reservation_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_persons_per_reservation', models.IntegerField(default=1, null=True)),
                ('maximum_persons_per_reservation', models.IntegerField(default=30, null=True)),
                ('maximum_reservations_in_waitlist', models.IntegerField(default=60, null=True)),
                ('close_reservation', models.IntegerField(default=2, null=True)),
                ('close_reservation_interval', models.CharField(blank=True, choices=[('hour', 'hour'), ('minute', 'minutes'), ('day', 'days'), ('week', 'weeks'), ('month', 'months'), ('year', 'years')], default='day', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
