# Generated by Django 5.0.12 on 2025-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0030_eventreservationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservationsettings',
            name='close_reservation_interval',
            field=models.CharField(blank=True, choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hour'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years'), ('at_start', 'at start'), ('on_end', 'when ended')], default='days', max_length=50, null=True),
        ),
    ]
