# Generated by Django 5.0.12 on 2025-03-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0032_alter_eventreservationsettings_close_reservation_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventreservationsettings',
            options={'verbose_name': 'event reservation settings', 'verbose_name_plural': 'event reservation settings'},
        ),
    ]
