# Generated by Django 5.0.12 on 2025-03-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0033_alter_eventreservationsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
