# Generated by Django 5.0.12 on 2025-03-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0034_reservation_customer_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventreservationsettings',
            old_name='close_reservation',
            new_name='close_reservation_time_amount',
        ),
    ]
