# Generated by Django 5.0.12 on 2025-03-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0036_alter_eventreservationsettings_close_reservation_time_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
