# Generated by Django 5.0.12 on 2025-03-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0037_alter_reservation_customer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
