# Generated by Django 5.0.12 on 2025-03-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_organizationemployee'),
        ('reservations', '0038_alter_reservation_customer_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreservationsettings',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
