# Generated by Django 5.0.12 on 2025-03-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0039_eventreservationsettings_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreservationsettings',
            name='always_show_progress_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventreservationsettings',
            name='show_progress_bar_when_x_percentage_reached',
            field=models.IntegerField(blank=True, default=65, null=True),
        ),
    ]
