# Generated by Django 5.0.12 on 2025-03-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0040_eventreservationsettings_always_show_progress_bar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='on_waitinglist_since',
            field=models.DateTimeField(blank=True, help_text='the moment the reservation has been added to the waitinglist', null=True, verbose_name='on waitinglist since'),
        ),
    ]
