# Generated by Django 5.0.12 on 2025-03-25 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_organizationemployee'),
        ('reservations', '0041_reservation_on_waitinglist_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='organizations.organization', verbose_name='organization'),
        ),
    ]
