# Generated by Django 5.0.12 on 2025-03-27 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0051_organizationpaymentmethod_cashpaymentmethod_and_more'),
        ('reservations', '0042_reservation_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentrequest'),
        ),
    ]
