# Generated by Django 5.0.12 on 2025-04-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0045_reservationupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCancel',
            fields=[
                ('reservationupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservationupdate')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('reservations.reservationupdate',),
        ),
        migrations.CreateModel(
            name='OrganizationConfirm',
            fields=[
                ('reservationupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservationupdate')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('reservations.reservationupdate',),
        ),
        migrations.CreateModel(
            name='OrganizationRefuse',
            fields=[
                ('reservationupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservationupdate')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('reservations.reservationupdate',),
        ),
        migrations.CreateModel(
            name='RequesterCancel',
            fields=[
                ('reservationupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservationupdate')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('reservations.reservationupdate',),
        ),
        migrations.CreateModel(
            name='RequesterConfirm',
            fields=[
                ('reservationupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservationupdate')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('reservations.reservationupdate',),
        ),
    ]
