# Generated by Django 5.0.12 on 2025-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0046_organizationcancel_organizationconfirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrefuse',
            name='custom_reason',
            field=models.TextField(blank=True, default='', verbose_name='custom reason'),
        ),
        migrations.AddField(
            model_name='organizationrefuse',
            name='reason',
            field=models.CharField(choices=[('EVENT_FULL', 'event full'), ('PERSON_BLOCKED', 'person blocked'), ('CUSTOM_REASON', 'custom reason'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=50, null=True, verbose_name='segment'),
        ),
    ]
