# Generated by Django 5.0.12 on 2025-04-16 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0028_alter_mailnotification_language_and_more'),
        ('reservations', '0047_organizationrefuse_custom_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationupdate',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='reservationupdate',
            name='send_notification',
            field=models.BooleanField(null=True, verbose_name='send notification'),
        ),
        migrations.AlterField(
            model_name='organizationrefuse',
            name='reason',
            field=models.CharField(choices=[('EVENT_FULL', 'event full'), ('PERSON_BLOCKED', 'person blocked'), ('CUSTOM_REASON', 'custom reason'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=50, null=True, verbose_name='reason'),
        ),
    ]
