# Generated by Django 5.0.12 on 2025-04-16 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0048_reservationupdate_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingUserEmailConfirmation',
            fields=[
                ('reservationupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservationupdate')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('reservations.reservationupdate',),
        ),
    ]
