# Generated by Django 5.0.12 on 2025-04-16 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0049_waitinguseremailconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidReservation',
            fields=[
                ('reservationupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservationupdate')),
                ('reason', models.CharField(choices=[('INVALID_EMAIL', 'invalid email'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=50, null=True, verbose_name='reason')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('reservations.reservationupdate',),
        ),
    ]
