# Generated by Django 5.0.12 on 2025-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0051_invalidreservation_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationupdate',
            options={'ordering': ['-created_on'], 'verbose_name': 'reservation update', 'verbose_name_plural': 'reservation updates'},
        ),
        migrations.AddField(
            model_name='reservationupdate',
            name='invalid_since',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='invalid since'),
        ),
        migrations.AddField(
            model_name='reservationupdate',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='is valid'),
        ),
    ]
