# Generated by Django 5.0.12 on 2025-04-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0052_alter_reservationupdate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationupdate',
            name='invalid_since',
        ),
        migrations.RemoveField(
            model_name='reservationupdate',
            name='is_valid',
        ),
    ]
