# Generated by Django 5.0.12 on 2025-04-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0053_remove_reservationupdate_invalid_since_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='confirmation_mail_sent_on',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='organization_confirmed_on',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='requester_confirmed_on',
        ),
    ]
