# Generated by Django 5.0.12 on 2025-04-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0054_remove_reservation_confirmation_mail_sent_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationupdate',
            name='notification',
        ),
    ]
