# Generated by Django 5.0.12 on 2025-04-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0055_remove_reservationupdate_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinguseremailconfirmation',
            name='email_confirmation_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
