# Generated by Django 5.0.12 on 2025-04-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0056_waitinguseremailconfirmation_email_confirmation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreservationsettings',
            name='telephone_number_required',
            field=models.BooleanField(default=True, verbose_name='telephone number required'),
        ),
        migrations.AlterField(
            model_name='eventreservationsettings',
            name='always_show_progress_bar',
            field=models.BooleanField(default=False, verbose_name='always show progress bar'),
        ),
        migrations.AlterField(
            model_name='eventreservationsettings',
            name='close_reservation_interval',
            field=models.CharField(blank=True, choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hour'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years'), ('at_start', 'at start'), ('on_end', 'when ended')], default='days', max_length=50, verbose_name='close reservation interval'),
        ),
        migrations.AlterField(
            model_name='eventreservationsettings',
            name='close_reservation_time_amount',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='close reservation time amount'),
        ),
        migrations.AlterField(
            model_name='eventreservationsettings',
            name='maximum_persons_per_reservation',
            field=models.IntegerField(default=30, null=True, verbose_name='maximum persons per reservation'),
        ),
        migrations.AlterField(
            model_name='eventreservationsettings',
            name='maximum_reservations_in_waitlist',
            field=models.IntegerField(default=60, null=True, verbose_name='maximum reservations in waitlist'),
        ),
        migrations.AlterField(
            model_name='eventreservationsettings',
            name='minimum_persons_per_reservation',
            field=models.IntegerField(default=1, null=True, verbose_name='minimum persons per reservation'),
        ),
        migrations.AlterField(
            model_name='eventreservationsettings',
            name='show_progress_bar_when_x_percentage_reached',
            field=models.IntegerField(blank=True, default=65, null=True, verbose_name='show progress bar when x percentage reached'),
        ),
    ]
