# Generated by Django 5.0.12 on 2025-04-18 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0057_eventreservationsettings_telephone_number_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTemporarilyRejected',
            fields=[
                ('reservationupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservationupdate')),
                ('reason', models.CharField(choices=[('EVENT_FULL', 'event full'), ('EVENT_FULL_BUT_ON_WAITINGLIST', 'event full but on waitinglist'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=50, null=True, verbose_name='reason')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('reservations.reservationupdate',),
        ),
    ]
