# Generated by Django 5.0.12 on 2025-04-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0058_organizationtemporarilyrejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidreservation',
            name='reason',
            field=models.CharField(choices=[('INVALID_EMAIL', 'invalid email'), ('NO_ACTIVE_ORGANIZATION', 'no active organization'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=50, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='organizationrefuse',
            name='reason',
            field=models.CharField(choices=[('EVENT_FULL', 'event full'), ('PERSON_BLOCKED', 'person blocked'), ('CUSTOM_REASON', 'custom reason'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=50, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='organizationtemporarilyrejected',
            name='reason',
            field=models.CharField(choices=[('EVENT_FULL', 'event full'), ('EVENT_FULL_BUT_ON_WAITINGLIST', 'event full but on waitinglist'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=50, verbose_name='reason'),
        ),
    ]
