# Generated by Django 5.0.12 on 2025-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0059_alter_invalidreservation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expired_on',
            field=models.DateTimeField(blank=True, help_text='the moment the reservation is no longer valid', null=True),
        ),
    ]
