# Generated by Django 5.0.12 on 2025-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0060_reservation_expired_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmed_on',
            field=models.DateTimeField(blank=True, help_text='the moment the reservation has been confirmed from both parties', null=True, verbose_name='confirmed on'),
        ),
    ]
