# Generated by Django 5.0.12 on 2025-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0062_alter_reservation_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(blank=True, help_text='the moment the reservation ends', null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(blank=True, help_text='the moment the reservation starts', null=True, verbose_name='start'),
        ),
    ]
