# Generated by Django 5.0.12 on 2025-04-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0063_reservation_end_reservation_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInvite',
            fields=[
                ('reservationupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservationupdate')),
                ('email_address', models.EmailField(blank=True, default='', max_length=254)),
                ('keep_it_secret', models.BooleanField(default=False, help_text='if true, we will never send any communication about the reservation to this guest')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('reservations.reservationupdate',),
        ),
    ]
