# Generated by Django 5.0.12 on 2025-04-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0064_guestinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestinvite',
            name='first_name',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='guestinvite',
            name='last_name',
            field=models.CharField(blank=True, default=''),
        ),
    ]
