# Generated by Django 5.0.12 on 2025-04-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0067_remove_guestinvite_last_name_guestinvite_family_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestinvite',
            name='keep_it_secret',
        ),
    ]
