# Generated by Django 5.0.12 on 2025-04-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0096_remove_concept_reservation_settings_and_more'),
        ('reservations', '0068_remove_guestinvite_keep_it_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventReservationSettings',
        ),
    ]
