# Generated by Django 5.0.12 on 2025-04-25 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0042_alter_organizationmember_person'),
        ('reservations', '0069_delete_eventreservationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number_required', models.BooleanField(default=True, verbose_name='telephone number required')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'reservation settings',
                'verbose_name_plural': 'reservation settings',
            },
        ),
        migrations.CreateModel(
            name='EventReservationSettings',
            fields=[
                ('reservationsettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservationsettings')),
                ('minimum_persons_per_reservation', models.IntegerField(default=1, null=True, verbose_name='minimum persons per reservation')),
                ('maximum_persons_per_reservation', models.IntegerField(default=30, null=True, verbose_name='maximum persons per reservation')),
                ('maximum_reservations_in_waitlist', models.IntegerField(default=60, null=True, verbose_name='maximum reservations in waitlist')),
                ('close_reservation_time_amount', models.IntegerField(blank=True, default=2, null=True, verbose_name='close reservation time amount')),
                ('close_reservation_interval', models.CharField(blank=True, choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hour'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years'), ('at_start', 'at start'), ('on_end', 'when ended')], default='days', max_length=50, verbose_name='close reservation interval')),
                ('always_show_progress_bar', models.BooleanField(default=False, verbose_name='always show progress bar')),
                ('show_progress_bar_when_x_percentage_reached', models.IntegerField(blank=True, default=65, null=True, verbose_name='show progress bar when x percentage reached')),
            ],
            options={
                'verbose_name': 'event reservation settings',
                'verbose_name_plural': 'event reservation settings',
            },
            bases=('reservations.reservationsettings',),
        ),
    ]
