# Generated by Django 5.0.12 on 2025-04-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0070_reservationsettings_eventreservationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestinvite',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
