# Generated by Django 5.0.12 on 2025-06-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0076_reservationsettings_requester_updates_allowed_until_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='allow_requester_updates_until',
            field=models.DateTimeField(blank=True, help_text='the moment until the requester can update the reservation', null=True, verbose_name='allow requester updates until'),
        ),
    ]
