# Generated by Django 5.0.12 on 2025-06-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0077_reservation_allow_requester_updates_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationsettings',
            name='requester_updates_allowed_until_interval',
        ),
        migrations.RemoveField(
            model_name='reservationsettings',
            name='requester_updates_allowed_until_time_amount',
        ),
        migrations.AddField(
            model_name='reservationsettings',
            name='allow_requester_updates_until_interval',
            field=models.CharField(blank=True, choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hour'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years'), ('at_start', 'at start'), ('on_end', 'when ended')], default='days', max_length=50, verbose_name='requester updates allowed until interval'),
        ),
        migrations.AddField(
            model_name='reservationsettings',
            name='allow_requester_updates_until_time_amount',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='requester updates allowed until time amount'),
        ),
    ]
