# Generated by Django 5.0.12 on 2025-03-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_device_delete_computer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.device')),
            ],
            options={
                'verbose_name': 'computer',
                'verbose_name_plural': 'computers',
            },
            bases=('hardware.device',),
        ),
    ]
