# Generated by Django 5.0.12 on 2025-03-28 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_computer'),
        ('organizations', '0022_organizationpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.organization', verbose_name='organization'),
        ),
    ]
