# Generated by Django 5.0.12 on 2025-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_computer_client_version_computer_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='tailscale_organization_name',
            field=models.CharField(blank=True, help_text='https://login.tailscale.com/admin/settings/general', null=True),
        ),
    ]
