# Generated by Django 5.0.12 on 2025-03-28 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_network_tailscale_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='hardware.network', verbose_name='network'),
        ),
    ]
