# Generated by Django 5.0.12 on 2025-03-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_computer_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='tailscale_api_key',
            field=models.CharField(blank=True, help_text='https://login.tailscale.com/admin/settings/keys', null=True),
        ),
    ]
