# Generated by Django 5.0.12 on 2025-04-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_alter_network_tailscale_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='computer',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='client_version',
            field=models.CharField(default='', editable=False, verbose_name='client version'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='expires',
            field=models.DateTimeField(editable=False, null=True, verbose_name='expires'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='hostname',
            field=models.CharField(default='', editable=False, verbose_name='hostname'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ip_addresses',
            field=models.CharField(default='', editable=False, verbose_name='ip addresses'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='last_seen',
            field=models.DateTimeField(editable=False, null=True, verbose_name='last seen'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='node_id',
            field=models.CharField(default='', editable=False, max_length=30, verbose_name='node id'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='update_available',
            field=models.BooleanField(default=False, verbose_name='update available'),
        ),
        migrations.AlterField(
            model_name='network',
            name='tailscale_api_key',
            field=models.CharField(blank=True, default='', help_text='https://login.tailscale.com/admin/settings/keys'),
        ),
        migrations.AlterField(
            model_name='network',
            name='tailscale_organization_name',
            field=models.CharField(blank=True, default='', help_text='https://login.tailscale.com/admin/settings/general'),
        ),
    ]
