# Generated by Django 5.0.12 on 2025-03-28 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='software.service')),
            ],
            options={
                'verbose_name': 'ollama service',
                'verbose_name_plural': 'ollama services',
            },
            bases=('software.service',),
        ),
    ]
