# Generated by Django 5.0.12 on 2025-03-28 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_alter_network_tailscale_api_key'),
        ('software', '0002_ollamaservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hardware.computer', verbose_name='computer'),
        ),
    ]
