# Generated by Django 5.0.12 on 2025-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_service_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ollamaservice',
            name='ai_model',
            field=models.CharField(default='mistral'),
        ),
        migrations.AddField(
            model_name='ollamaservice',
            name='port',
            field=models.IntegerField(default=11434),
        ),
    ]
