# Generated by Django 5.0.12 on 2025-05-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_basefile_created_by_basefile_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.basefile')),
                ('video', models.FileField(blank=True, help_text='Upload a video file', null=True, upload_to='uploads/videos/')),
                ('url', models.URLField(blank=True, default='', help_text='External video URL (YouTube, Vimeo, etc.)')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds (auto-extracted if self-hosted)', null=True)),
                ('source', models.CharField(blank=True, choices=[('upload', 'Self-hosted'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('other', 'Other')], default='', max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('files.basefile',),
        ),
    ]
