# Generated by Django 5.0.12 on 2025-05-15 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_videofile'),
        ('organizations', '0045_remove_organization_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='organizations.organization'),
        ),
    ]
