# Generated by Django 5.0.12 on 2025-05-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_basefile_organization'),
        ('organizations', '0045_remove_organization_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='basefile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='organizations.organization'),
        ),
    ]
