# Generated by Django 5.0.12 on 2025-05-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicholiday',
            name='timetable',
        ),
        migrations.CreateModel(
            name='TimetablePublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_holiday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='timetables.publicholiday')),
                ('timetable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='timetables.timetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimetablePublicHolidayTimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField(null=True)),
                ('to_time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('public_holiday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_public_holiday_time_blocks', to='timetables.timetablepublicholiday')),
            ],
            options={
                'get_latest_by': 'from_time',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PublicHolidayTimeBlock',
        ),
    ]
