# Generated by Django 5.0.12 on 2025-05-22 11:09

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_remove_publicholiday_timetable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='name_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
    ]
