# Generated by Django 5.0.12 on 2025-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_publicholiday_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='current_status',
            field=models.CharField(choices=[('ALWAYS_OPEN', 'always open'), ('ALWAYS_CLOSED', 'always closed'), ('EXCEPTIONALLY_CLOSED', 'exceptionally closed'), ('TIMETABLE_BASED', 'timetable based')], default='TIMETABLE_BASED', max_length=50),
        ),
    ]
