# Generated by Django 5.0.12 on 2025-05-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0005_timetable_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='is_always_closed',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='is_always_open',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='is_exceptionally_closed',
        ),
    ]
