# Generated by Django 5.0.12 on 2025-05-22 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0049_organizationaddress'),
        ('timetables', '0006_remove_timetable_is_always_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_list', to='organizations.organization'),
        ),
    ]
