# Generated by Django 5.0.12 on 2025-05-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0007_timetable_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablepublicholiday',
            name='holiday_status',
            field=models.CharField(choices=[('OPEN_AS_USUAL', 'open as usual'), ('CLOSED', 'closed'), ('SPECIAL_HOURS', 'special hours')], default='CLOSED', max_length=50),
        ),
    ]
