# Generated by Django 5.0.12 on 2025-05-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0008_timetablepublicholiday_holiday_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetablepublicholidaytimeblock',
            name='date',
        ),
    ]
