# Generated by Django 5.0.12 on 2025-05-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0010_alter_timeblock_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday'), ('EVERY_DAY', 'every day'), ('EVERY_WEEKDAY', 'every weekday'), ('EVERY_WEEKEND', 'every weekend'), ('EVERY_PUBLIC_HOLIDAY', 'every public holiday')], default='0', max_length=50),
        ),
    ]
