# Generated by Django 5.0.12 on 2025-05-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0012_alter_timeblock_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='is_always_closed_on_public_holidays',
        ),
    ]
