# Generated by Django 5.0.12 on 2025-05-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('timetables', '0014_timetablebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='from_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='from_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
