# Generated by Django 5.0.12 on 2025-05-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0016_remove_timetable_from_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
