# Generated by Django 5.0.12 on 2025-05-26 14:58

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0017_timetable_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='countries',
        ),
        migrations.AddField(
            model_name='timetable',
            name='country',
            field=django_countries.fields.CountryField(default='BE', max_length=2),
        ),
    ]
