# Generated by Django 5.0.12 on 2025-05-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0049_organizationaddress'),
        ('timetables', '0018_remove_timetable_countries_timetable_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'timetable', 'verbose_name_plural': 'timetables'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='organizations.organization'),
        ),
    ]
