# Generated by Django 5.0.12 on 2025-05-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0019_alter_timetable_options_alter_timetable_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeblock',
            old_name='from_time_table',
            new_name='time_table',
        ),
    ]
