# Generated by Django 5.0.12 on 2025-02-25 19:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('gps_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('street', models.TextField(blank=True, default='')),
                ('house_number', models.TextField(blank=True, default='')),
                ('bus', models.TextField(blank=True, default='')),
                ('postal_code', models.TextField(blank=True, default='')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
