# Generated by Django 5.0.12 on 2025-02-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_alter_address_bus_alter_address_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default=''),
        ),
    ]
