# Generated by Django 5.0.12 on 2025-02-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='gps_address',
            field=models.CharField(editable=False, null=True),
        ),
    ]
