# Generated by Django 5.0.12 on 2025-03-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('floor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geography.floor')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('geography.floor',),
        ),
        migrations.AddField(
            model_name='floor',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
