# Generated by Django 5.0.12 on 2025-03-25 10:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0009_floor_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='surface',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
