# Generated by Django 5.0.12 on 2025-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0010_alter_floor_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='card_description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='floor',
            name='card_description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='floor',
            name='card_description_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='floor',
            name='card_description_nl',
            field=models.TextField(blank=True, default='', null=True, verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='floor',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='floor',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='floor',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='floor',
            name='name_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
