# Generated by Django 5.0.12 on 2025-03-31 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0011_floor_card_description_de_floor_card_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrace',
            fields=[
                ('floor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geography.floor')),
            ],
            options={
                'verbose_name': 'terrace',
                'verbose_name_plural': 'terraces',
            },
            bases=('geography.floor',),
        ),
    ]
