# Generated by Django 5.0.12 on 2025-05-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0014_floor_transition_floor_transition_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='transition_durtion',
            field=models.IntegerField(default=1500, help_text='in milliseconds', verbose_name='transition duration'),
        ),
    ]
