# Generated by Django 5.0.12 on 2025-05-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0016_rename_transition_durtion_floor_transition_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
