# Generated by Django 5.0.12 on 2025-06-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0113_eventfloor_floor_layout_alter_eventfloor_floor'),
        ('geography', '0017_address_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='in_building',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='terrace',
            name='floor_ptr',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor_ptr',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Terrace',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
