# Generated by Django 5.0.12 on 2025-05-14 08:14

import autoslug.fields
import django.db.models.deletion
import scaleos.stores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0044_organizationstyling_primary_button_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'purchasable item',
                'verbose_name_plural': 'purchasable items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('purchasableitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stores.purchasableitem')),
                ('ean', models.CharField(blank=True, help_text='enter the 13-digit EAN code.', max_length=13, null=True, unique=True, validators=[scaleos.stores.validators.validate_ean])),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
            bases=('stores.purchasableitem',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('purchasableitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stores.purchasableitem')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
            bases=('stores.purchasableitem',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
            },
        ),
    ]
