# Generated by Django 5.0.12 on 2025-05-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
