# Generated by Django 5.0.12 on 2025-02-07 17:25

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('national_number', models.CharField(blank=True, null=True)),
                ('middle_name', models.CharField(blank=True, null=True)),
                ('family_name', models.CharField(null=True)),
                ('nationality', models.CharField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('primary_mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('primary_telephone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('primary_email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mother_tongue', models.CharField(blank=True, choices=[('en', 'English'), ('fr-fr', 'French'), ('nl', 'Dutch')], max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
