# Generated by Django 5.0.12 on 2025-02-07 18:48

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_person_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
