# Generated by Django 5.0.12 on 2025-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_person_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_number',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.CharField(blank=True, default=''),
        ),
    ]
