# Generated by Django 5.0.12 on 2025-02-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_person_mother_tongue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
    ]
