# Generated by Django 5.0.12 on 2025-02-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_person_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
