# Generated by Django 5.0.12 on 2025-02-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_personaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default=''),
        ),
    ]
