# Generated by Django 5.0.12 on 2025-03-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_remove_person_slug_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mother_tongue',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('nl', 'Dutch')], default='', max_length=50),
        ),
    ]
