# Generated by Django 5.0.12 on 2025-03-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_alter_person_mother_tongue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mother_tongue',
            field=models.CharField(blank=True, choices=[('en', '%s - %s'), ('fr', 'French'), ('nl', 'Dutch')], default='', max_length=50),
        ),
    ]
