# Generated by Django 5.0.12 on 2025-03-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_personlanguage_persontelephonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlanguage',
            name='is_mother_tongue',
            field=models.BooleanField(default=False),
        ),
    ]
