# Generated by Django 5.0.12 on 2025-03-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_personlanguage_created_by_personlanguage_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='primary_telephone_number',
        ),
    ]
