# Generated by Django 5.0.12 on 2025-03-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_remove_person_primary_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mother_tongue',
            field=models.CharField(blank=True, choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personlanguage',
            name='language',
            field=models.CharField(blank=True, choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50, verbose_name='Language'),
        ),
    ]
