# Generated by Django 5.0.12 on 2025-04-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_alter_personaddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlanguage',
            name='language',
            field=models.CharField(blank=True, choices=[('nl', 'Nederlands'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='', max_length=50, verbose_name='language'),
        ),
    ]
