# Generated by Django 5.0.12 on 2025-04-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_alter_personlanguage_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(default='', verbose_name='family name'),
        ),
    ]
