# Generated by Django 5.0.12 on 2025-02-07 11:18

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='registered_country',
            field=django_countries.fields.CountryField(default='BE', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
