# Generated by Django 5.0.12 on 2025-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_organization_registered_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='registration_id',
            field=models.CharField(blank=True, default=''),
        ),
    ]
