# Generated by Django 5.0.12 on 2025-02-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_enterprise_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
    ]
