# Generated by Django 5.0.12 on 2025-02-12 13:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='gps_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
