# Generated by Django 5.0.12 on 2025-02-26 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_personaddress'),
        ('organizations', '0008_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
