# Generated by Django 5.0.12 on 2025-02-26 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_personaddress'),
        ('organizations', '0009_organizationowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationowner',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owning_organizations', to='hr.person'),
        ),
    ]
