# Generated by Django 5.0.12 on 2025-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_organization_card_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
