# Generated by Django 5.0.12 on 2025-03-12 14:19

import scaleos.shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_alter_organization_card_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcustomer',
            name='card_description',
            field=models.TextField(blank=True, default='', verbose_name='card description'),
        ),
        migrations.AddField(
            model_name='organizationcustomer',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to=scaleos.shared.models.CardModel.model_directory_path, verbose_name='card image'),
        ),
    ]
