# Generated by Django 5.0.12 on 2025-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_organizationcustomer_card_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='name'),
        ),
    ]
