# Generated by Django 5.0.12 on 2025-03-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
