# Generated by Django 5.0.12 on 2025-03-18 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_organization_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationowner',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='organizations.organization'),
        ),
    ]
