# Generated by Django 5.0.12 on 2025-03-26 11:40

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_organizationemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStyling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/logos/')),
                ('fav_icon', models.ImageField(blank=True, null=True, upload_to='organization/fav_icons/')),
                ('primary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('organization', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styling', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
