# Generated by Django 5.0.12 on 2025-03-28 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_alter_network_tailscale_api_key'),
        ('organizations', '0022_organizationpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='network',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='hardware.network', verbose_name='network'),
        ),
    ]
