# Generated by Django 5.0.12 on 2025-04-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_organization_network'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationcustomer',
            options={'verbose_name': 'organization customer', 'verbose_name_plural': 'organization customers'},
        ),
        migrations.AddField(
            model_name='organizationcustomer',
            name='is_b2b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationcustomer',
            name='is_b2c',
            field=models.BooleanField(default=False),
        ),
    ]
