# Generated by Django 5.0.12 on 2025-04-02 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_alter_person_mother_tongue_and_more'),
        ('organizations', '0024_alter_organizationcustomer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationcustomer',
            name='person',
        ),
        migrations.AddField(
            model_name='organizationcustomer',
            name='b2b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2b_customers', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationcustomer',
            name='b2c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_at_organizations', to='hr.person'),
        ),
        migrations.AlterField(
            model_name='organizationcustomer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization'),
        ),
    ]
