# Generated by Django 5.0.12 on 2025-04-02 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_remove_organizationcustomer_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcustomer',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization'),
        ),
    ]
