# Generated by Django 5.0.12 on 2025-04-02 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_alter_organizationcustomer_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcustomer',
            name='b2b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.organization'),
        ),
    ]
