# Generated by Django 5.0.12 on 2025-04-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0028_organization_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='url',
        ),
        migrations.AddField(
            model_name='organization',
            name='internal_url',
            field=models.URLField(blank=True, help_text='used for sending mails and notifications', null=True),
        ),
    ]
