# Generated by Django 5.0.12 on 2025-04-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_computer_created_computer_is_active_and_more'),
        ('organizations', '0029_remove_organization_url_organization_internal_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='network',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='hardware.network', verbose_name='network'),
        ),
    ]
