# Generated by Django 5.0.12 on 2025-04-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0091_remove_customerconcept_customer'),
        ('organizations', '0031_organizationmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationemployee',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationemployee',
            name='person',
        ),
        migrations.RemoveField(
            model_name='organizationowner',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationowner',
            name='person',
        ),
        migrations.DeleteModel(
            name='OrganizationCustomer',
        ),
        migrations.DeleteModel(
            name='OrganizationEmployee',
        ),
        migrations.DeleteModel(
            name='OrganizationOwner',
        ),
    ]
