# Generated by Django 5.0.12 on 2025-04-24 10:26

import django.db.models.deletion
import scaleos.shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0034_organizationemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCustomer',
            fields=[
                ('organizationmember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organizationmember')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to=scaleos.shared.models.CardModel.model_directory_path, verbose_name='card image')),
                ('card_description', models.TextField(blank=True, default='', verbose_name='card description')),
            ],
            options={
                'verbose_name': 'organization customer',
                'verbose_name_plural': 'organization customers',
            },
            bases=('organizations.organizationmember', models.Model),
        ),
        migrations.CreateModel(
            name='B2BCustomer',
            fields=[
                ('organizationcustomer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organizationcustomer')),
                ('b2b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'b2b customer',
                'verbose_name_plural': 'b2b customers',
            },
            bases=('organizations.organizationcustomer',),
        ),
    ]
