# Generated by Django 5.0.12 on 2025-04-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0035_organizationcustomer_b2bcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationcustomer',
            name='card_description',
        ),
        migrations.RemoveField(
            model_name='organizationcustomer',
            name='card_image',
        ),
    ]
