# Generated by Django 5.0.12 on 2025-04-24 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_alter_personlanguage_language'),
        ('organizations', '0036_remove_organizationcustomer_card_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hr.person'),
        ),
    ]
