# Generated by Django 5.0.12 on 2025-04-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_alter_personlanguage_modified_by_and_more'),
        ('organizations', '0038_alter_organizationmember_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'verbose_name': 'organization member', 'verbose_name_plural': 'organization members'},
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'person')},
        ),
    ]
