# Generated by Django 5.0.12 on 2025-04-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0039_alter_organizationmember_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together=set(),
        ),
    ]
