# Generated by Django 5.0.12 on 2025-04-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0040_alter_organizationmember_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationemployee',
            options={'verbose_name': 'organization employee', 'verbose_name_plural': 'organization employees'},
        ),
        migrations.AlterModelOptions(
            name='organizationowner',
            options={'verbose_name': 'organization owner', 'verbose_name_plural': 'organization owners'},
        ),
    ]
