# Generated by Django 5.0.12 on 2025-04-24 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_alter_personlanguage_modified_by_and_more'),
        ('organizations', '0041_alter_organizationemployee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hr.person', verbose_name='person'),
        ),
    ]
