# Generated by Django 5.0.12 on 2025-05-05 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0042_alter_organizationmember_person'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='websites.website', verbose_name='website'),
        ),
    ]
