# Generated by Django 5.0.12 on 2025-05-07 06:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0043_organization_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstyling',
            name='primary_button_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='organizationstyling',
            name='primary_button_text_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
