# Generated by Django 5.0.12 on 2025-05-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0044_organizationstyling_primary_button_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
    ]
