# Generated by Django 5.0.12 on 2025-05-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0047_organization_transition_durtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='transition_durtion',
            new_name='transition_duration',
        ),
    ]
