# Generated by Django 5.0.12 on 2025-05-19 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0016_rename_transition_durtion_floor_transition_duration'),
        ('organizations', '0048_rename_transition_durtion_organization_transition_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.address', verbose_name='address')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
