# Generated by Django 5.0.12 on 2025-06-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0049_organizationaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationPaymentMethod',
        ),
    ]
