# Generated by Django 5.0.12 on 2025-06-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0110_remove_customerconcept_customer'),
        ('organizations', '0050_delete_organizationpaymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationcustomer',
            name='organizationmember_ptr',
        ),
        migrations.DeleteModel(
            name='B2BCustomer',
        ),
        migrations.DeleteModel(
            name='OrganizationCustomer',
        ),
    ]
