# Generated by Django 5.0.12 on 2025-06-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hr', '0025_alter_person_birthday'),
        ('organizations', '0051_remove_organizationcustomer_organizationmember_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='B2BCustomer',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.customer')),
                ('b2b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_customers', to='organizations.organization')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('organizations.customer',),
        ),
        migrations.CreateModel(
            name='B2CCustomer',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.customer')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2c_customers', to='hr.person', verbose_name='person')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('organizations.customer',),
        ),
    ]
