# Generated by Django 5.0.12 on 2025-06-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0052_customer_b2bcustomer_b2ccustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bcustomer',
            name='b2b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2b_customers', to='organizations.organization'),
        ),
    ]
