# Generated by Django 5.0.12 on 2025-06-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0053_alter_b2bcustomer_b2b'),
        ('websites', '0037_remove_website_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='primary_website',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_org', to='websites.website'),
        ),
    ]
