# Generated by Django 5.0.12 on 2025-06-06 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0054_organization_primary_website'),
        ('websites', '0039_website_primary_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='primary_website',
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_domain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_organization', to='websites.websitedomain'),
        ),
    ]
