# Generated by Django 5.0.12 on 2025-05-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='publish_from',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='publish_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
