# Generated by Django 5.0.12 on 2025-05-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_page_publish_from_page_publish_till'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='show_in_menu',
            new_name='show_in_main_menu',
        ),
    ]
