# Generated by Django 5.0.12 on 2025-05-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_rename_show_in_menu_page_show_in_main_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='domain_name',
            field=models.CharField(max_length=255, verbose_name='domain name'),
        ),
        migrations.AlterField(
            model_name='website',
            name='homepage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage', to='websites.page', verbose_name='homepage'),
        ),
        migrations.AlterField(
            model_name='website',
            name='slogan',
            field=models.CharField(blank=True, default='', verbose_name='slogan'),
        ),
    ]
