# Generated by Django 5.0.12 on 2025-05-05 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_alter_website_domain_name_alter_website_homepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_pages', to='websites.page'),
        ),
    ]
