# Generated by Django 5.0.12 on 2025-05-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_block_publish_from_block_publish_till'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'block', 'verbose_name_plural': 'blocks'},
        ),
        migrations.AddField(
            model_name='block',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='websites.website'),
        ),
    ]
