# Generated by Django 5.0.12 on 2025-05-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_alter_block_options_block_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllConceptsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.block')),
            ],
            options={
                'verbose_name': 'all concept block',
                'verbose_name_plural': 'all concepts blocks',
            },
            bases=('websites.block',),
        ),
        migrations.CreateModel(
            name='B2BConceptsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.block')),
            ],
            options={
                'verbose_name': 'b2b concept block',
                'verbose_name_plural': 'b2b concepts blocks',
            },
            bases=('websites.block',),
        ),
        migrations.CreateModel(
            name='B2CConceptsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.block')),
            ],
            options={
                'verbose_name': 'b2c concept block',
                'verbose_name_plural': 'b2c concepts blocks',
            },
            bases=('websites.block',),
        ),
    ]
