# Generated by Django 5.0.12 on 2025-05-05 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0008_allconceptsblock_b2bconceptsblock_b2cconceptsblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllB2BConceptsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.block')),
            ],
            options={
                'verbose_name': 'all b2b concept block',
                'verbose_name_plural': 'all b2b concepts blocks',
            },
            bases=('websites.block',),
        ),
        migrations.CreateModel(
            name='AllB2CConceptsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.block')),
            ],
            options={
                'verbose_name': 'all b2c concept block',
                'verbose_name_plural': 'all b2c concepts blocks',
            },
            bases=('websites.block',),
        ),
        migrations.RemoveField(
            model_name='b2cconceptsblock',
            name='block_ptr',
        ),
        migrations.DeleteModel(
            name='B2BConceptsBlock',
        ),
        migrations.DeleteModel(
            name='B2CConceptsBlock',
        ),
    ]
