# Generated by Django 5.0.12 on 2025-05-06 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_allb2bconceptsblock_allb2cconceptsblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.block')),
            ],
            options={
                'verbose_name': 'all concept block',
                'verbose_name_plural': 'all concepts blocks',
            },
            bases=('websites.block',),
        ),
        migrations.RemoveField(
            model_name='allb2cconceptsblock',
            name='block_ptr',
        ),
        migrations.RemoveField(
            model_name='allconceptsblock',
            name='block_ptr',
        ),
        migrations.DeleteModel(
            name='AllB2BConceptsBlock',
        ),
        migrations.DeleteModel(
            name='AllB2CConceptsBlock',
        ),
        migrations.DeleteModel(
            name='AllConceptsBlock',
        ),
    ]
