# Generated by Django 5.0.12 on 2025-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0010_conceptsblock_remove_allb2cconceptsblock_block_ptr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptsblock',
            options={'verbose_name': 'concept block', 'verbose_name_plural': 'concepts blocks'},
        ),
        migrations.AddField(
            model_name='conceptsblock',
            name='filter',
            field=models.CharField(choices=[('ALL', 'show all'), ('B2B', 'show only b2b'), ('B2C', 'show only b2c')], default='ALL', max_length=50),
        ),
    ]
