# Generated by Django 5.0.12 on 2025-05-06 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0011_alter_conceptsblock_options_conceptsblock_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.block')),
            ],
            options={
                'verbose_name': 'events block',
                'verbose_name_plural': 'events blocks',
            },
            bases=('websites.block',),
        ),
    ]
