# Generated by Django 5.0.12 on 2025-05-06 08:53

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0013_page_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
                ('image', models.ImageField(upload_to='websites/images/', verbose_name='image')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='websites.website', verbose_name='website')),
            ],
            options={
                'verbose_name': 'website image',
                'verbose_name_plural': 'website images',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.websiteimage'),
        ),
    ]
