# Generated by Django 5.0.12 on 2025-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0014_websiteimage_page_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteimage',
            name='alt_text',
            field=models.CharField(default='', max_length=255, verbose_name='alt text'),
        ),
    ]
