# Generated by Django 5.0.12 on 2025-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0015_websiteimage_alt_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'website', 'verbose_name_plural': 'websites'},
        ),
        migrations.AddField(
            model_name='website',
            name='ask_segment',
            field=models.BooleanField(default=False),
        ),
    ]
