# Generated by Django 5.0.12 on 2025-05-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0016_alter_website_options_website_ask_segment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='header_height',
            new_name='banner_height',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='header_image',
            new_name='banner_image',
        ),
    ]
