# Generated by Django 5.0.12 on 2025-05-06 19:35

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('websites', '0017_rename_header_height_page_banner_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_from', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
                ('publish_till', models.DateTimeField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'call to action',
                'verbose_name_plural': 'call to actions',
            },
        ),
        migrations.CreateModel(
            name='VisitExternalURL',
            fields=[
                ('calltoaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.calltoaction')),
                ('url', models.URLField(default='', verbose_name='url')),
            ],
            options={
                'verbose_name': 'visit external url',
                'verbose_name_plural': 'visit external urls',
            },
            bases=('websites.calltoaction',),
        ),
        migrations.CreateModel(
            name='VisitPage',
            fields=[
                ('calltoaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.calltoaction')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.page')),
            ],
            options={
                'verbose_name': 'visit page',
                'verbose_name_plural': 'visit pages',
            },
            bases=('websites.calltoaction',),
        ),
    ]
