# Generated by Django 5.0.12 on 2025-05-06 19:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0018_calltoaction_visitexternalurl_visitpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default='#00000000', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='button_text',
            field=models.CharField(default='', max_length=255, verbose_name='button text'),
        ),
    ]
