# Generated by Django 5.0.12 on 2025-05-06 19:46

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0019_calltoaction_button_color_calltoaction_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAVisitExternalURL',
            fields=[
                ('calltoaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.calltoaction')),
                ('url', models.URLField(default='', verbose_name='url')),
            ],
            options={
                'verbose_name': 'visit external url',
                'verbose_name_plural': 'visit external urls',
            },
            bases=('websites.calltoaction',),
        ),
        migrations.RemoveField(
            model_name='visitpage',
            name='calltoaction_ptr',
        ),
        migrations.RemoveField(
            model_name='visitpage',
            name='page',
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='button_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.CreateModel(
            name='CTAVisitPage',
            fields=[
                ('calltoaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.calltoaction')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.page')),
            ],
            options={
                'verbose_name': 'visit page',
                'verbose_name_plural': 'visit pages',
            },
            bases=('websites.calltoaction',),
        ),
        migrations.DeleteModel(
            name='VisitExternalURL',
        ),
        migrations.DeleteModel(
            name='VisitPage',
        ),
    ]
