# Generated by Django 5.0.12 on 2025-05-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0020_ctavisitexternalurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToActionBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.block')),
            ],
            options={
                'verbose_name': 'call to action block',
                'verbose_name_plural': 'call to action blocks',
            },
            bases=('websites.block',),
        ),
        migrations.CreateModel(
            name='CallToActionBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordering')),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='websites.calltoactionblock')),
                ('call_to_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.calltoaction')),
            ],
            options={
                'verbose_name': 'call to action block item',
                'verbose_name_plural': 'call to action block items',
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
