# Generated by Django 5.0.12 on 2025-05-07 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0044_organizationstyling_primary_button_color_and_more'),
        ('websites', '0021_calltoactionblock_calltoactionblockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_to_actions', to='organizations.organization', verbose_name='organization'),
        ),
    ]
