# Generated by Django 5.0.12 on 2025-05-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0022_calltoaction_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltoaction',
            name='organization',
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_to_actions', to='websites.website', verbose_name='website'),
        ),
    ]
