# Generated by Django 5.0.12 on 2025-05-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0023_remove_calltoaction_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slogan',
        ),
        migrations.AddField(
            model_name='page',
            name='banner_slogan',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='banner_title',
            field=models.CharField(blank=True, default=''),
        ),
    ]
