# Generated by Django 5.0.12 on 2025-05-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0024_remove_page_slogan_page_banner_slogan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAndTextBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='websites.block')),
                ('text', models.TextField(blank=True, default='')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.websiteimage')),
            ],
            options={
                'verbose_name': 'image and text block',
                'verbose_name_plural': 'image and text blocks',
            },
            bases=('websites.block',),
        ),
    ]
