# Generated by Django 5.0.12 on 2025-05-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0025_imageandtextblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageandtextblock',
            name='image_alignment',
            field=models.CharField(choices=[('LEFT', 'left'), ('RIGHT', 'right')], default='LEFT', max_length=5),
        ),
    ]
