# Generated by Django 5.0.12 on 2025-05-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0045_remove_organization_website'),
        ('websites', '0026_imageandtextblock_image_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website', to='organizations.organization', verbose_name='organization'),
        ),
    ]
