# Generated by Django 5.0.12 on 2025-05-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_videofile'),
        ('websites', '0027_website_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.imagefile'),
        ),
    ]
