# Generated by Django 5.0.12 on 2025-05-16 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_basefile_checksum'),
        ('websites', '0028_alter_page_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageandtextblock',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_and_text_blocks', to='files.imagefile'),
        ),
    ]
