# Generated by Django 5.0.12 on 2025-05-19 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0029_alter_imageandtextblock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoactionblockitem',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='websites.block'),
        ),
        migrations.DeleteModel(
            name='CallToActionBlock',
        ),
    ]
