# Generated by Django 5.0.12 on 2025-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0031_alter_calltoactionblockitem_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
