# Generated by Django 5.0.12 on 2025-05-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0032_block_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
