# Generated by Django 5.0.12 on 2025-06-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0033_page_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True, verbose_name='domain name')),
            ],
            options={
                'verbose_name': 'domain name',
                'verbose_name_plural': 'domain names',
            },
        ),
        migrations.CreateModel(
            name='WebsiteDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('website', models.ForeignKey(blank=True, help_text='leave blank if default website needs to be shown', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='websites.website')),
            ],
            options={
                'verbose_name': 'website domain',
                'verbose_name_plural': 'website domains',
            },
        ),
    ]
