# Generated by Django 5.0.12 on 2025-06-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0034_domainname_websitedomain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomainName',
        ),
    ]
