# Generated by Django 5.0.12 on 2025-06-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0035_delete_domainname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitedomain',
            name='domain_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='domain name'),
        ),
        migrations.AlterField(
            model_name='websitedomain',
            name='website',
            field=models.ForeignKey(blank=True, help_text='leave blank if default website needs to be shown', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='websites.website', verbose_name='website'),
        ),
    ]
