# Generated by Django 5.0.12 on 2025-06-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0036_alter_websitedomain_domain_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='domain_name',
        ),
    ]
