# Generated by Django 5.0.12 on 2025-06-06 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0054_organization_primary_website'),
        ('websites', '0037_remove_website_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='organizations.organization', verbose_name='organization'),
        ),
    ]
