# Generated by Django 5.0.12 on 2025-02-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'get_latest_by': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='price',
            name='created',
        ),
        migrations.RemoveField(
            model_name='price',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='modified',
        ),
        migrations.AddField(
            model_name='price',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
