# Generated by Django 5.0.12 on 2025-02-07 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_price_options_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgePriceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgePriceMatrixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_age', models.IntegerField(blank=True, null=True)),
                ('till_age', models.IntegerField(blank=True, null=True)),
                ('age_price_matrix', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='payments.agepricematrix')),
                ('price', models.OneToOneField(help_text='will pay', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
