# Generated by Django 5.0.12 on 2025-02-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_agepricematrix_agepricematrixitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='agepricematrix',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
