# Generated by Django 5.0.12 on 2025-02-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_price_public_key'),
        ('reservations', '0007_remove_brunchreservation_age_price_matrix_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='agepricematrixitem',
            name='age_price_matrix',
        ),
        migrations.RemoveField(
            model_name='agepricematrixitem',
            name='price',
        ),
        migrations.DeleteModel(
            name='AgePriceMatrix',
        ),
        migrations.DeleteModel(
            name='AgePriceMatrixItem',
        ),
    ]
