# Generated by Django 5.0.12 on 2025-02-08 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_pricematrix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgePriceMatrix',
            fields=[
                ('pricematrix_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.pricematrix')),
            ],
            options={
                'get_latest_by': ['created_on'],
                'abstract': False,
            },
            bases=('payments.pricematrix',),
        ),
        migrations.CreateModel(
            name='AgePriceMatrixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_age', models.IntegerField(blank=True, null=True)),
                ('till_age', models.IntegerField(blank=True, null=True)),
                ('age_price_matrix', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='payments.agepricematrix')),
                ('price', models.OneToOneField(help_text='will pay', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
