# Generated by Django 5.0.12 on 2025-02-08 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_agepricematrix_agepricematrixitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPriceMatrix',
            fields=[
                ('pricematrix_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.pricematrix')),
            ],
            options={
                'get_latest_by': ['created_on'],
                'abstract': False,
            },
            bases=('payments.pricematrix',),
        ),
        migrations.CreateModel(
            name='BulkPriceMatrixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordering')),
                ('from_number_of_items', models.IntegerField(blank=True, help_text='from number of items', null=True)),
                ('to_number_of_items', models.IntegerField(blank=True, help_text='to number of items', null=True)),
                ('amount', models.IntegerField(default=1, help_text='You get')),
                ('bulk_price_matrix', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='payments.bulkpricematrix')),
                ('price', models.OneToOneField(help_text='for the price of', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.price')),
            ],
            options={
                'verbose_name': 'bulk price matrix items',
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
