# Generated by Django 5.0.12 on 2025-02-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_agepricematrix_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricematrix',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='pricematrix',
            name='valid_till',
        ),
    ]
