# Generated by Django 5.0.12 on 2025-02-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_pricematrix_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkpricematrixitem',
            options={'ordering': ['ordering'], 'verbose_name': 'bulk price matrix item', 'verbose_name_plural': 'bulk price matrix items'},
        ),
    ]
