# Generated by Django 5.0.12 on 2025-02-10 14:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_bulkpricematrixitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricematrix',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
    ]
