# Generated by Django 5.0.12 on 2025-02-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_pricematrix_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricematrix',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
