# Generated by Django 5.0.12 on 2025-02-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0015_pricematrix_public_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agepricematrixitem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='agepricematrixitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bulkpricematrixitem',
            name='id',
        ),
        migrations.CreateModel(
            name='PriceMatrixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='agepricematrixitem',
            name='pricematrixitem_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.pricematrixitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkpricematrixitem',
            name='pricematrixitem_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.pricematrixitem'),
            preserve_default=False,
        ),
    ]
