# Generated by Django 5.0.12 on 2025-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_agepricematrixitem_maximum_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agepricematrixitem',
            name='maximum_persons',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
