# Generated by Django 5.0.12 on 2025-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_alter_agepricematrixitem_maximum_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agepricematrixitem',
            name='minimum_persons',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
