# Generated by Django 5.0.12 on 2025-02-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_alter_price_options_remove_pricehistory_old_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='current_price_currency',
        ),
    ]
