# Generated by Django 5.0.12 on 2025-02-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_remove_pricehistory_includes_vat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-created_on']},
        ),
    ]
