# Generated by Django 5.0.12 on 2025-03-12 20:58

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_payment_amount_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EUR', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_received',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EUR', max_digits=15, null=True),
        ),
    ]
