# Generated by Django 5.0.12 on 2025-03-12 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0036_alter_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentrequest'),
        ),
        migrations.DeleteModel(
            name='PaymentRequestPayment',
        ),
    ]
