# Generated by Django 5.0.12 on 2025-03-12 22:33

import django.db.models.deletion
import localflavor.generic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0037_payment_payment_request_delete_paymentrequestpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCMoneyTransferPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.payment')),
                ('from_iban', localflavor.generic.models.IBANField(blank=True, include_countries=('AD', 'AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM', 'VA'), max_length=34, null=True, use_nordea_extensions=False)),
                ('to_iban', localflavor.generic.models.IBANField(include_countries=('AD', 'AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM', 'VA'), max_length=34, null=True, use_nordea_extensions=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('payments.payment',),
        ),
    ]
