# Generated by Django 5.0.12 on 2025-03-20 08:04

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0039_alter_pricematrix_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricematrixitem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='pricematrixitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
