# Generated by Django 5.0.12 on 2025-03-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0040_pricematrixitem_name_pricematrixitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricematrixitem',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='pricematrixitem',
            name='name_fr_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='pricematrixitem',
            name='name_nl',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
    ]
