# Generated by Django 5.0.12 on 2025-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0042_rename_name_fr_fr_pricematrixitem_name_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricematrixitem',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='pricematrixitem',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='pricematrixitem',
            name='name_it',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='name'),
        ),
    ]
