# Generated by Django 5.0.12 on 2025-03-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0043_pricematrixitem_name_de_pricematrixitem_name_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricematrixitem',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='pricematrixitem',
            name='name_it',
        ),
    ]
