# Generated by Django 5.0.12 on 2025-03-27 09:56

import django.db.models.deletion
import scaleos.shared.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0044_remove_pricematrixitem_name_es_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='vat_percentage',
            field=models.IntegerField(default=21, validators=[scaleos.shared.validators.validate_percentage]),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='vat_percentage',
            field=models.IntegerField(default=21, validators=[scaleos.shared.validators.validate_percentage]),
        ),
        migrations.CreateModel(
            name='PaymentReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('percentage_of_total_price', models.IntegerField(blank=True, null=True, validators=[scaleos.shared.validators.validate_percentage])),
                ('prepayment_type', models.CharField(choices=[('FIXED', 'fixed'), ('PERCENTAGE', 'percentage')], default='FIXED', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fixed_price', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.price')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment reservation settings',
                'verbose_name_plural': 'payment reservation settings',
            },
        ),
    ]
