# Generated by Django 5.0.12 on 2025-03-27 10:11

import django.db.models.deletion
import scaleos.shared.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0046_paymentreservationsettings_only_when_group_exceeds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreservationsettings',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='paymentreservationsettings',
            name='only_when_group_exceeds',
        ),
        migrations.RemoveField(
            model_name='paymentreservationsettings',
            name='percentage_of_total_price',
        ),
        migrations.RemoveField(
            model_name='paymentreservationsettings',
            name='prepayment_type',
        ),
        migrations.CreateModel(
            name='PrePaymentReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('prepayment_type', models.CharField(choices=[('FIXED', 'fixed'), ('PERCENTAGE', 'percentage')], default='FIXED', max_length=20)),
                ('only_when_group_exceeds', models.IntegerField(blank=True, help_text='number of persons', null=True)),
                ('percentage_of_total_price', models.IntegerField(blank=True, null=True, validators=[scaleos.shared.validators.validate_percentage])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fixed_price', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.price')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prepayment reservation settings',
                'verbose_name_plural': 'prepayment reservation settings',
            },
        ),
    ]
