# Generated by Django 5.0.12 on 2025-03-27 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0047_remove_paymentreservationsettings_fixed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='origin_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='origin_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
