# Generated by Django 5.0.12 on 2025-03-27 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_remove_person_primary_telephone_number'),
        ('organizations', '0021_organizationstyling'),
        ('payments', '0049_payment_origin_content_type_payment_origin_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='to_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='to organization'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='to_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.person', verbose_name='to person'),
        ),
        migrations.AlterField(
            model_name='bulkpricematrixitem',
            name='from_number_of_items',
            field=models.IntegerField(blank=True, help_text='from number of items', null=True, verbose_name='from number of items'),
        ),
        migrations.AlterField(
            model_name='bulkpricematrixitem',
            name='price',
            field=models.OneToOneField(help_text='for the price of', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.price', verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='bulkpricematrixitem',
            name='to_number_of_items',
            field=models.IntegerField(blank=True, help_text='to number of items', null=True, verbose_name='to number of items'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='to_pay',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.price', verbose_name='to pay'),
        ),
    ]
