# Generated by Django 5.0.12 on 2025-03-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0051_organizationpaymentmethod_cashpaymentmethod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epcmoneytransferpaymentmethod',
            name='organizationpaymentmethod_ptr',
        ),
        migrations.RemoveField(
            model_name='organizationpaymentmethod',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='organizationpaymentmethod',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='organizationpaymentmethod',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationpaymentmethod',
            name='polymorphic_ctype',
        ),
        migrations.DeleteModel(
            name='CashPaymentMethod',
        ),
        migrations.DeleteModel(
            name='EPCMoneyTransferPaymentMethod',
        ),
        migrations.DeleteModel(
            name='OrganizationPaymentMethod',
        ),
    ]
