# Generated by Django 5.0.12 on 2025-03-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0053_paymentmethod_cashpaymentmethod_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationPaymentMethod',
        ),
    ]
