# Generated by Django 5.0.12 on 2025-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0054_delete_organizationpaymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashpaymentmethod',
            options={'verbose_name': 'cash', 'verbose_name_plural': 'cash'},
        ),
        migrations.AlterModelOptions(
            name='epcmoneytransferpaymentmethod',
            options={'verbose_name': 'EPC money transfer', 'verbose_name_plural': 'EPC money transfer'},
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
