# Generated by Django 5.0.12 on 2025-03-27 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0058_prepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepayment',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='due date & time'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.price', verbose_name='price'),
        ),
    ]
