# Generated by Django 5.0.12 on 2025-03-28 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0059_remove_prepayment_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='origin_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='price',
            name='origin_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
