# Generated by Django 5.0.12 on 2025-03-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0060_price_origin_content_type_price_origin_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='origin_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
