# Generated by Django 5.0.12 on 2025-03-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0061_alter_price_origin_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepayment',
            name='price',
        ),
    ]
