# Generated by Django 5.0.12 on 2025-03-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0062_remove_prepayment_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepayment',
            options={'verbose_name': 'prepayment', 'verbose_name_plural': 'prepayments'},
        ),
        migrations.RemoveField(
            model_name='agepricematrixitem',
            name='price',
        ),
    ]
