# Generated by Django 5.0.12 on 2025-03-28 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_organizationpaymentmethod'),
        ('payments', '0063_alter_prepayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='organizations.organization'),
        ),
    ]
