# Generated by Django 5.0.12 on 2025-03-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0065_alter_price_origin_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkpricematrixitem',
            name='price',
        ),
    ]
