# Generated by Django 5.0.12 on 2025-03-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0066_remove_bulkpricematrixitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricematrixitem',
            name='show_matrix_name_in_item_name',
            field=models.BooleanField(default=True),
        ),
    ]
