# Generated by Django 5.0.12 on 2025-03-28 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_organizationpaymentmethod'),
        ('payments', '0068_remove_pricematrixitem_show_matrix_name_in_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaymentreservationsettings',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepayment_settings', to='organizations.organization', verbose_name='organization'),
        ),
    ]
