# Generated by Django 5.0.12 on 2025-03-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0069_prepaymentreservationsettings_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepaymentreservationsettings',
            name='fixed_price',
        ),
    ]
