# Generated by Django 5.0.12 on 2025-03-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0070_remove_prepaymentreservationsettings_fixed_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='to_pay',
        ),
    ]
