# Generated by Django 5.0.12 on 2025-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0073_remove_price_origin_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='unique_origin_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
