# Generated by Django 5.0.12 on 2025-03-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0074_alter_price_unique_origin_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'price', 'verbose_name_plural': 'prices'},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('unique_origin_content_type', 'unique_origin_object_id')},
        ),
    ]
