# Generated by Django 5.0.12 on 2025-03-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0075_alter_price_options_alter_price_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaymentreservationsettings',
            name='to_be_paid_amount',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='prepaymentreservationsettings',
            name='to_be_paid_interval',
            field=models.CharField(blank=True, choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hour'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years'), ('at_start', 'at start'), ('on_end', 'when ended')], default='days', max_length=50),
        ),
        migrations.AlterField(
            model_name='prepaymentreservationsettings',
            name='prepayment_type',
            field=models.CharField(choices=[('FULL_PRICE', 'full price'), ('FIXED', 'fixed'), ('PERCENTAGE', 'percentage')], default='FIXED', max_length=20),
        ),
    ]
