# Generated by Django 5.0.12 on 2025-03-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0076_prepaymentreservationsettings_to_be_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaymentreservationsettings',
            name='to_be_paid_amount',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='prepaymentreservationsettings',
            name='to_be_paid_interval',
            field=models.CharField(choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hour'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years'), ('at_start', 'at start'), ('on_end', 'when ended')], default='days', max_length=50),
        ),
    ]
