# Generated by Django 5.0.12 on 2025-03-29 08:47

import django.db.models.deletion
import scaleos.shared.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0071_remove_concept_prepayment_settings_and_more'),
        ('organizations', '0023_organization_network'),
        ('payments', '0077_alter_prepaymentreservationsettings_to_be_paid_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReservationPrepaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('to_be_paid_amount', models.IntegerField(default=5, null=True)),
                ('to_be_paid_interval', models.CharField(choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hour'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years'), ('at_start', 'at start'), ('on_end', 'when ended')], default='days', max_length=50)),
                ('prepayment_type', models.CharField(choices=[('FULL_PRICE', 'full price'), ('FIXED', 'fixed'), ('PERCENTAGE', 'percentage')], default='FIXED', max_length=20)),
                ('only_when_group_exceeds', models.IntegerField(blank=True, help_text='number of persons', null=True)),
                ('percentage_of_total_price', models.IntegerField(blank=True, null=True, validators=[scaleos.shared.validators.validate_percentage])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepayment_settings', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'prepayment reservation settings',
                'verbose_name_plural': 'prepayment reservation settings',
            },
        ),
        migrations.DeleteModel(
            name='PrePaymentReservationSettings',
        ),
    ]
