# Generated by Django 5.0.12 on 2025-03-29 09:01

import django.db.models.deletion
import scaleos.shared.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0078_eventreservationprepaymentsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventreservationprepaymentsettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventreservationprepaymentsettings',
            name='only_when_group_exceeds',
        ),
        migrations.RemoveField(
            model_name='eventreservationprepaymentsettings',
            name='percentage_of_total_price',
        ),
        migrations.RemoveField(
            model_name='eventreservationprepaymentsettings',
            name='prepayment_type',
        ),
        migrations.RemoveField(
            model_name='eventreservationprepaymentsettings',
            name='to_be_paid_amount',
        ),
        migrations.RemoveField(
            model_name='eventreservationprepaymentsettings',
            name='to_be_paid_interval',
        ),
        migrations.CreateModel(
            name='EventReservationPrepaymentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('to_be_paid_amount', models.IntegerField(default=5, null=True)),
                ('to_be_paid_interval', models.CharField(choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hour'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years'), ('at_start', 'at start'), ('on_end', 'when ended')], default='days', max_length=50)),
                ('prepayment_type', models.CharField(choices=[('FULL_PRICE', 'full price'), ('FIXED', 'fixed'), ('PERCENTAGE', 'percentage')], default='FIXED', max_length=20)),
                ('only_when_group_exceeds', models.IntegerField(blank=True, help_text='number of persons', null=True)),
                ('percentage_of_total_price', models.IntegerField(blank=True, null=True, validators=[scaleos.shared.validators.validate_percentage])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_reservation_prepayment_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.eventreservationprepaymentsettings', verbose_name='event reservation prepayment settings')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event reservation prepayment settings',
                'verbose_name_plural': 'event reservation prepayment settings',
            },
        ),
    ]
