# Generated by Django 5.0.12 on 2025-03-30 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0080_remove_eventreservationprepaymentsettings_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventreservationpaymentcondition',
            options={'verbose_name': 'event reservation payment settings', 'verbose_name_plural': 'event reservation payment settings'},
        ),
        migrations.AlterField(
            model_name='eventreservationpaymentcondition',
            name='event_reservation_payment_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.eventreservationpaymentsettings', verbose_name='event reservation payment settings'),
        ),
    ]
