# Generated by Django 5.0.12 on 2025-03-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0081_alter_eventreservationpaymentcondition_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreservationpaymentcondition',
            name='to_be_paid_amount',
        ),
        migrations.AddField(
            model_name='eventreservationpaymentcondition',
            name='payment_moment',
            field=models.CharField(choices=[('BEFORE_START_OF_EVENT', 'before the start of the event'), ('AFTER_START_OF_EVENT', 'after the start of the event'), ('BEFORE_END_OF_EVENT', 'before the event ends'), ('AFTER_END_OF_EVENT', 'after the event ended'), ('ON_START_OF_EVENT', 'on start of the event'), ('AT_END_OF_EVENT', 'at the end of the event')], default='BEFORE_START_OF_EVENT', max_length=50),
        ),
        migrations.AddField(
            model_name='eventreservationpaymentcondition',
            name='to_be_paid_time_amount',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='eventreservationpaymentcondition',
            name='to_be_paid_interval',
            field=models.CharField(choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hour'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], default='days', max_length=50),
        ),
    ]
