# Generated by Django 5.0.12 on 2025-03-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0082_remove_eventreservationpaymentcondition_to_be_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreservationpaymentcondition',
            name='is_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventreservationpaymentcondition',
            name='payment_moment',
            field=models.CharField(choices=[('BEFORE_START_OF_EVENT', 'before the start of the event'), ('AFTER_START_OF_EVENT', 'after the start of the event'), ('BEFORE_END_OF_EVENT', 'before the event ends'), ('AFTER_END_OF_EVENT', 'after the event ended'), ('AT_START_OF_EVENT', 'at the start of the event'), ('AT_END_OF_EVENT', 'at the end of the event')], default='BEFORE_START_OF_EVENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventreservationpaymentcondition',
            name='prepayment_type',
            field=models.CharField(choices=[('FULL_PRICE', 'full price'), ('FIXED_PRICE', 'fixed price'), ('PERCENTAGE_OF_TOTAL_PRICE', 'PERCENTAGE_OF_TOTAL_PRICE'), ('REMAINING_PRICE', 'remaining price')], default='FIXED_PRICE', max_length=40),
        ),
        migrations.DeleteModel(
            name='PaymentReservationSettings',
        ),
    ]
