# Generated by Django 5.0.12 on 2025-03-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0083_eventreservationpaymentcondition_is_warranty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservationpaymentcondition',
            name='event_reservation_payment_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='payments.eventreservationpaymentsettings', verbose_name='event reservation payment settings'),
        ),
        migrations.AlterField(
            model_name='eventreservationpaymentcondition',
            name='prepayment_type',
            field=models.CharField(choices=[('FULL_PRICE', 'full price'), ('FIXED_PRICE', 'fixed price'), ('PERCENTAGE_OF_TOTAL_PRICE', 'percentage of total price'), ('REMAINING_PRICE', 'remaining price')], default='FIXED_PRICE', max_length=40),
        ),
    ]
