# Generated by Django 5.0.12 on 2025-03-31 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0087_eventreservationpaymentsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentsettings', verbose_name='payment settings'),
        ),
    ]
