# Generated by Django 5.0.12 on 2025-03-31 11:54

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0089_prepayment_created_by_prepayment_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='current_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=15, null=True),
        ),
    ]
