# Generated by Django 5.0.12 on 2025-03-31 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0090_alter_price_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayment', to='payments.price', verbose_name='price'),
        ),
    ]
