# Generated by Django 5.0.12 on 2025-03-31 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0091_prepayment_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('origin_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('due_datetime', models.DateTimeField(blank=True, null=True, verbose_name='due date & time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifications', to=settings.AUTH_USER_MODEL)),
                ('origin_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('payment_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proposals', to='payments.paymentrequest', verbose_name='payment request')),
                ('price', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='payments.price', verbose_name='price')),
            ],
            options={
                'verbose_name': 'payment proposal',
                'verbose_name_plural': 'payment proposals',
            },
        ),
        migrations.DeleteModel(
            name='PrePayment',
        ),
    ]
