# Generated by Django 5.0.12 on 2025-03-31 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0092_paymentproposal_delete_prepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproposal',
            name='price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='payments.price', verbose_name='price'),
        ),
    ]
