# Generated by Django 5.0.12 on 2025-04-01 06:28

import scaleos.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0093_alter_paymentproposal_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-created_on'], 'verbose_name': 'price', 'verbose_name_plural': 'prices'},
        ),
        migrations.RemoveField(
            model_name='voucherpaymentmethod',
            name='polymorphic_ctype',
        ),
        migrations.AlterField(
            model_name='eventreservationpaymentcondition',
            name='percentage_of_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[scaleos.shared.validators.validate_percentage]),
        ),
    ]
