# Generated by Django 5.0.12 on 2025-04-01 06:28

import scaleos.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0094_alter_price_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservationpaymentcondition',
            name='percentage_of_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[scaleos.shared.validators.validate_percentage]),
        ),
    ]
