# Generated by Django 5.0.12 on 2025-04-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0095_alter_eventreservationpaymentcondition_percentage_of_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='public_key',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
