# Generated by Django 5.0.12 on 2025-04-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0097_remove_price_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='includes_vat',
            field=models.BooleanField(default=True),
        ),
    ]
