# Generated by Django 5.0.12 on 2025-04-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0098_pricehistory_includes_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='mixed_vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='mixed_vat',
            field=models.BooleanField(default=False),
        ),
    ]
