# Generated by Django 5.0.12 on 2025-04-07 16:04

import scaleos.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0099_price_mixed_vat_pricehistory_mixed_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='vat_percentage',
            field=models.IntegerField(blank=True, default=21, null=True, validators=[scaleos.shared.validators.validate_percentage]),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='vat_percentage',
            field=models.IntegerField(blank=True, default=21, null=True, validators=[scaleos.shared.validators.validate_percentage]),
        ),
    ]
