# Generated by Django 5.0.12 on 2025-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0100_alter_price_vat_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='includes_vat',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='includes_vat',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
