# Generated by Django 5.0.12 on 2025-04-07 16:11

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0101_alter_price_includes_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='input_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=15, null=True),
        ),
    ]
