# Generated by Django 5.0.12 on 2025-04-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0102_alter_price_input_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='mixed_vat',
            field=models.BooleanField(default=False, help_text="if mixed vat, it's always including vat"),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='mixed_vat',
            field=models.BooleanField(default=False, help_text="if mixed vat, it's always including vat"),
        ),
        migrations.DeleteModel(
            name='VoucherPaymentMethod',
        ),
    ]
