# Generated by Django 5.0.12 on 2025-04-15 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0103_alter_price_mixed_vat_alter_pricehistory_mixed_vat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPaymentMethod',
            fields=[
                ('paymentmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.paymentmethod')),
            ],
            options={
                'verbose_name': 'voucher',
                'verbose_name_plural': 'vouchers',
            },
            bases=('payments.paymentmethod',),
        ),
    ]
