# Generated by Django 5.0.12 on 2025-04-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0106_vatpriceline_input_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vatpriceline',
            options={'ordering': ['-created_on'], 'verbose_name': 'VAT price line', 'verbose_name_plural': 'VAT price lines'},
        ),
    ]
