# Generated by Django 5.0.12 on 2025-04-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0107_alter_vatpriceline_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='input_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='input_price_currency',
        ),
    ]
