# Generated by Django 5.0.12 on 2025-04-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0108_remove_price_input_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='includes_vat',
        ),
        migrations.RemoveField(
            model_name='price',
            name='mixed_vat',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='includes_vat',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='mixed_vat',
        ),
        migrations.RemoveField(
            model_name='vatpriceline',
            name='includes_vat',
        ),
        migrations.RemoveField(
            model_name='vatpriceline',
            name='mixed_vat',
        ),
    ]
