# Generated by Django 5.0.12 on 2025-04-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0109_remove_price_includes_vat_remove_price_mixed_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatpriceline',
            name='includes_vat',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
