# Generated by Django 5.0.12 on 2025-04-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0110_vatpriceline_includes_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='vat_percentage',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='vat_percentage',
        ),
    ]
