# Generated by Django 5.0.12 on 2025-04-15 14:02

import scaleos.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0111_remove_price_vat_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatpriceline',
            name='includes_vat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vatpriceline',
            name='vat_percentage',
            field=models.IntegerField(blank=True, null=True, validators=[scaleos.shared.validators.validate_percentage]),
        ),
    ]
