# Generated by Django 5.0.12 on 2025-04-15 14:04

import scaleos.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0112_alter_vatpriceline_includes_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatpriceline',
            name='includes_vat',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vatpriceline',
            name='vat_percentage',
            field=models.IntegerField(null=True, validators=[scaleos.shared.validators.validate_percentage]),
        ),
    ]
