# Generated by Django 5.0.12 on 2025-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0114_alter_eventreservationpaymentcondition_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreservationpaymentcondition',
            name='payment_moment',
            field=models.CharField(choices=[('BEFORE_START_OF_EVENT', 'before the start of the event'), ('AFTER_START_OF_EVENT', 'after the start of the event'), ('BEFORE_END_OF_EVENT', 'before the event ends'), ('AFTER_END_OF_EVENT', 'after the event ended'), ('AT_START_OF_EVENT', 'at the start of the event'), ('AT_END_OF_EVENT', 'at the end of the event'), ('AFTER_RESERVATION_CONFRIMATION', 'after the reservation confirmation')], default='BEFORE_START_OF_EVENT', max_length=50),
        ),
    ]
