# Generated by Django 5.0.12 on 2025-04-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0115_alter_eventreservationpaymentcondition_payment_moment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventReservationPaymentCondition',
        ),
    ]
