# Generated by Django 5.0.12 on 2025-04-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0117_paymentcondition_eventreservationpaymentcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='structured_reference',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='eventreservationpaymentcondition',
            name='prepayment_type',
            field=models.CharField(choices=[('FULL_PRICE', 'full price'), ('FIXED_PRICE', 'fixed price'), ('FIXED_PRICE_PER_PERSON', 'fixed price per person'), ('PERCENTAGE_OF_TOTAL_PRICE', 'percentage of total price'), ('REMAINING_PRICE', 'remaining price')], default='FIXED_PRICE', max_length=40),
        ),
    ]
