# Generated by Django 5.0.12 on 2025-04-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0118_paymentrequest_structured_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='structured_reference',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='structured_reference_be',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='structured_reference_sepa',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True),
        ),
    ]
