# Generated by Django 5.0.12 on 2025-05-26 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0120_remove_epcmoneytransferpayment_to_iban_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MolliePaymentMethod',
            fields=[
                ('paymentmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.paymentmethod')),
                ('api_key', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Mollie',
                'verbose_name_plural': 'Mollie',
            },
            bases=('payments.paymentmethod',),
        ),
    ]
