# Generated by Django 5.0.12 on 2025-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0121_molliepaymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molliepaymentmethod',
            name='api_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
