# Generated by Django 5.0.12 on 2025-06-02 11:22

import scaleos.shared.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0122_alter_molliepaymentmethod_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molliepaymentmethod',
            name='api_key',
            field=scaleos.shared.fields.EncryptedTextField(),
        ),
    ]
