# Generated by Django 5.0.12 on 2025-06-02 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0049_organizationaddress'),
        ('payments', '0123_alter_molliepaymentmethod_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='organization'),
        ),
    ]
