# Generated by Django 5.0.12 on 2025-06-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0050_delete_organizationpaymentmethod'),
        ('payments', '0124_paymentmethod_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='organizations.organization', verbose_name='organization'),
        ),
    ]
