# Generated by Django 5.0.12 on 2025-06-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0125_alter_paymentmethod_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epcmoneytransferpaymentmethod',
            options={'verbose_name': 'EPC Money Transfer', 'verbose_name_plural': 'EPC Money Transfer'},
        ),
    ]
